FROM debian:stable-slim
RUN apt-get update && apt-get install -y curl git && apt-get clean
RUN useradd -m lean
USER lean
WORKDIR /home/lean
ENV PATH="/home/lean/.elan/bin:$PATH"
RUN curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
RUN elan default leanprover/lean4:v4.18.0
RUN lake --version && lean --version
