-- Task: (see IR JSON)
-- Verdict: regular
-- Template: prove_regular_via_dfa

--
-- Однако построить явный ДКА или регулярное выражение также не удалось из-за сложности взаимодействия всех возможных длин w и позиционного ограничения |z1| < |z2|.
-- 
-- 5) Агент замыкания не смог выделить нерегулярное ядро при пересечении с регулярными языками.
-- 
-- 4) Агент Нероуда не смог построить бесконечное семейство попарно различимых слов: свободный выбор z1 (непустой префикс) нейтрализует попытки различить слова.
-- 
-- 3) Агент накачки не смог найти ни одного слова, для которого накачка приводила бы к противоречию: экзистенциальный квантор по разбиению (z1, w, z2) слишком гибок — при увеличении длины строки всегда находится подходящее разбиение.
-- 
-- 2) При w длины 2 добавляются паттерны: «abaabb» (w=ab), «baaabb» (w=aa), «bbaabb» (w=bb), «baabab» (w=ba). При w длины 3 и более — ещё больше паттернов.
-- 
-- 1) При w длины 1 паттерн w·a·w·b даёт подстроки «aaab» (w=a) и «babb» (w=b). Любая строка, содержащая «aaab» или «babb» в качестве подстроки, принадлежит L при условии, что подстрока расположена достаточно далеко от правого конца (чтобы выполнялось |z1| < |z2|).
-- 
-- Обоснование гипотезы:
-- 
-- Ни один из агентов не смог построить полное доказательство. Гипотеза: язык L = {z1·w·a·w·b·z2 | z1,w,z2 ∈ {a,b}+, |z1| < |z2|} является регулярным.
--
-- Generated by TFL Agent System
-- Fill in the sorry placeholders to complete the proof.

/-
  Template: Prove regularity by constructing a DFA.

  Self-contained — no imports, no Mathlib.
  FILL markers indicate placeholders for the Formalizer Agent.
  All FILL sections use `sorry` so the file compiles as-is.
-/

-- ===== Base definitions (from RegLang.lean) =====

structure DFA (Alpha : Type) (State : Type) where
  step : State → Alpha → State
  start : State
  accept : State → Bool

namespace DFA

def run (M : DFA Alpha State) (w : List Alpha) : State :=
  w.foldl M.step M.start

def accepts (M : DFA Alpha State) (w : List Alpha) : Bool :=
  M.accept (M.run w)

end DFA

def Language (Alpha : Type) := List Alpha → Prop

def IsRegular {Alpha : Type} (L : Language Alpha) : Prop :=
  ∃ (n : Nat) (M : DFA Alpha (Fin n)),
    ∀ w, M.accepts w = true ↔ L w

-- ===== Template begins =====

-- FILL: Define alphabet (e.g., Fin 2 for {a, b})
abbrev Alpha : Type := Fin 2

-- FILL: Number of DFA states
abbrev numStates : Nat := 3  -- «NUM_STATES»

-- FILL: State type
abbrev Q : Type := Fin numStates

-- FILL: Transition function
def delta : Q → Alpha → Q := sorry  -- «STATE_TRANSITIONS»

-- FILL: Start state
def q0 : Q := ⟨0, by decide⟩  -- «START»

-- FILL: Accept predicate
def isAccept : Q → Bool := sorry  -- «ACCEPT_STATES»

/-- The constructed DFA. -/
def myDFA : DFA Alpha Q where
  step := delta
  start := q0
  accept := isAccept

-- FILL: Language predicate (the language we claim the DFA recognises)
def languagePred : Language Alpha := sorry  -- «LANGUAGE_PREDICATE»

-- FILL: Correctness — the DFA recognises exactly `languagePred`
theorem dfa_correct (w : List Alpha) :
    myDFA.accepts w = true ↔ languagePred w := by
  sorry  -- «PROOF»

/-- Corollary: the language is regular. -/
theorem language_is_regular : IsRegular (Alpha := Alpha) languagePred :=
  ⟨numStates, myDFA, dfa_correct⟩
