/-
  Language: L generated by the grammar S → SaSb | ε | A, A → bb | aa | bSb
  Proof: non-regular via the Myhill–Nerode theorem.

  Alphabet mapping: a = 0, b = 1

  Strategy:
    We exhibit the infinite family of words {a^i | i ≥ 1}.
    For any i ≠ j (i, j ≥ 1), the suffix z = b^(i+1) distinguishes them:
      • a^(i+1) · b^(i+1) = a^(i+1) b^(i+1) ∈ L
      • a^(j+1) · b^(i+1) = a^(j+1) b^(i+1) ∉ L  (since j+1 ≠ i+1)
    Hence the Myhill–Nerode equivalence has infinite index, so L is not regular.
-/

-- ===== Base definitions (self-contained, no Mathlib) =====

structure DFA (Alpha : Type) (State : Type) where
  step : State → Alpha → State
  start : State
  accept : State → Bool

namespace DFA

def run (M : DFA Alpha State) (w : List Alpha) : State :=
  w.foldl M.step M.start

def accepts (M : DFA Alpha State) (w : List Alpha) : Bool :=
  M.accept (M.run w)

end DFA

def Language (Alpha : Type) := List Alpha → Prop

def IsRegular {Alpha : Type} (L : Language Alpha) : Prop :=
  ∃ (n : Nat) (M : DFA Alpha (Fin n)),
    ∀ w, M.accepts w = true ↔ L w

-- ===== Alphabet =====

-- a = 0, b = 1
abbrev Alpha : Type := Fin 2

-- ===== Grammar definition (inductive) =====

/--
  Inductive characterisation of the language generated by:
    S → SaSb | ε | A
    A → bb | aa | bSb
  We define membership in L as an inductive predicate on `List (Fin 2)`.
-/
inductive InLang : List Alpha → Prop where
  | eps : InLang []
  | sasb : ∀ (w₁ w₂ : List Alpha),
      InLang w₁ → InLang w₂ →
      InLang (w₁ ++ [0] ++ w₂ ++ [1])
  | aa : InLang [0, 0]
  | bb : InLang [1, 1]
  | bsb : ∀ (w : List Alpha),
      InLang w →
      InLang ([1] ++ w ++ [1])

-- The language predicate
def languagePred : Language Alpha := fun w => InLang w

-- ===== Infinite family of words =====

-- words i = a^(i+1), i.e., List.replicate (i+1) 0
def words : Nat → List Alpha :=
  fun i => List.replicate (i + 1) (0 : Alpha)

-- ===== Distinguishing suffixes =====

-- For pair (i, j) with i ≠ j, the distinguishing suffix is b^(i+1).
def distinguisher : Nat → Nat → List Alpha :=
  fun i _j => List.replicate (i + 1) (1 : Alpha)

-- ===== Key lemma: a^n b^n ∈ L for all n =====

theorem replicate_succ_append {α : Type} (n : Nat) (a : α) :
    List.replicate (n + 1) a = [a] ++ List.replicate n a := by
  simp [List.replicate_succ]

theorem anbn_in_lang (n : Nat) :
    InLang (List.replicate n (0 : Alpha) ++ List.replicate n (1 : Alpha)) := by
  induction n with
  | zero => simp; exact InLang.eps
  | succ k ih =>
    -- a^(k+1) b^(k+1) = [] ++ [0] ++ (a^k b^k) ++ [1]
    -- Using S → S₁ a S₂ b with S₁ = ε, S₂ = a^k b^k
    have h : List.replicate (k + 1) (0 : Fin 2) ++ List.replicate (k + 1) (1 : Fin 2)
           = [] ++ [0] ++ (List.replicate k (0 : Fin 2) ++ List.replicate k (1 : Fin 2)) ++ [1] := by
      simp [List.replicate_succ]
      constructor
      · rfl
      · rw [List.append_assoc]
    rw [h]
    exact InLang.sasb [] (List.replicate k 0 ++ List.replicate k 1) InLang.eps ih

-- ===== Counting function for balanced proof =====

-- Count occurrences of a value in a list
def countVal {α : Type} [DecidableEq α] (a : α) : List α → Nat
  | [] => 0
  | x :: xs => (if x = a then 1 else 0) + countVal a xs

theorem countVal_nil {α : Type} [DecidableEq α] (a : α) :
    countVal a [] = 0 := rfl

theorem countVal_cons {α : Type} [DecidableEq α] (a x : α) (xs : List α) :
    countVal a (x :: xs) = (if x = a then 1 else 0) + countVal a xs := rfl

theorem countVal_append {α : Type} [DecidableEq α] (a : α) (l₁ l₂ : List α) :
    countVal a (l₁ ++ l₂) = countVal a l₁ + countVal a l₂ := by
  induction l₁ with
  | nil => simp [countVal_nil]
  | cons x xs ih =>
    simp only [List.cons_append, countVal_cons, ih]
    omega

theorem countVal_replicate_same {α : Type} [DecidableEq α] (a : α) (n : Nat) :
    countVal a (List.replicate n a) = n := by
  induction n with
  | zero => simp [countVal_nil]
  | succ k ih =>
    simp only [List.replicate_succ, countVal_cons, if_pos rfl, ih]

theorem countVal_replicate_diff {α : Type} [DecidableEq α] (a b : α) (n : Nat) (hab : a ≠ b) :
    countVal a (List.replicate n b) = 0 := by
  induction n with
  | zero => simp [countVal_nil]
  | succ k ih =>
    simp only [List.replicate_succ, countVal_cons, if_neg (Ne.symm hab ▸ hab), ih]
    split
    · next h => exact absurd h hab
    · simp [ih]

theorem countVal_singleton_same {α : Type} [DecidableEq α] (a : α) :
    countVal a [a] = 1 := by
  simp [countVal_cons, countVal_nil]

theorem countVal_singleton_diff {α : Type} [DecidableEq α] (a b : α) (hab : a ≠ b) :
    countVal a [b] = 0 := by
  simp [countVal_cons, countVal_nil, if_neg hab]

-- ===== Key invariant: count of 0s equals count of 1s in any word in L =====

theorem inlang_balanced (w : List Alpha) (hw : InLang w) :
    countVal 0 w = countVal 1 w := by
  induction hw with
  | eps => rfl
  | sasb w₁ w₂ _ _ ih₁ ih₂ =>
    simp only [countVal_append, countVal_cons, countVal_nil]
    have h0 : (0 : Fin 2) = (0 : Fin 2) := rfl
    have h1 : (1 : Fin 2) = (1 : Fin 2) := rfl
    have h01 : (0 : Fin 2) ≠ (1 : Fin 2) := by decide
    have h10 : (1 : Fin 2) ≠ (0 : Fin 2) := by decide
    simp only [if_pos h0, if_neg h01, if_pos h1, if_neg h10]
    omega
  | aa =>
    simp only [countVal_cons, countVal_nil]
    decide
  | bb =>
    simp only [countVal_cons, countVal_nil]
    decide
  | bsb w _ ih =>
    simp only [countVal_append, countVal_cons, countVal_nil]
    have h01 : (0 : Fin 2) ≠ (1 : Fin 2) := by decide
    have h10 : (1 : Fin 2) ≠ (0 : Fin 2) := by decide
    have h1 : (1 : Fin 2) = (1 : Fin 2) := rfl
    have h0 : (0 : Fin 2) = (0 : Fin 2) := rfl
    simp only [if_neg h01, if_pos h0, if_neg h10, if_pos h1]
    omega

-- ===== If a^m b^p ∈ L with m, p ≥ 1, then m = p =====

theorem inlang_ab_balanced (m p : Nat) (hm : m ≥ 1) (hp : p ≥ 1)
    (hw : InLang (List.replicate m (0 : Alpha) ++ List.replicate p (1 : Alpha))) :
    m = p := by
  have hbal := inlang_balanced _ hw
  have h01 : (0 : Fin 2) ≠ (1 : Fin 2) := by decide
  have h10 : (1 : Fin 2) ≠ (0 : Fin 2) := by decide
  rw [countVal_append, countVal_append] at hbal
  rw [countVal_replicate_same, countVal_replicate_diff 0 1 p h01] at hbal
  rw [countVal_replicate_diff 1 0 m h10, countVal_replicate_same] at hbal
  omega

-- ===== words i produces the right replicate form =====

theorem words_append_distinguisher (i : Nat) :
    words i ++ distinguisher i i =
    List.replicate (i + 1) (0 : Alpha) ++ List.replicate (i + 1) (1 : Alpha) := by
  rfl

-- ===== Pairwise distinguishability =====

theorem pairwise_distinct (i j : Nat) (hij : i ≠ j) :
    ∃ z : List Alpha,
      languagePred (words i ++ z) ↔ ¬ languagePred (words j ++ z) := by
  use distinguisher i j
  unfold languagePred words distinguisher
  constructor
  · -- Forward: a^(i+1) b^(i+1) ∈ L → a^(j+1) b^(i+1) ∉ L
    intro _
    intro hj
    have : j + 1 = i + 1 := inlang_ab_balanced (j + 1) (i + 1)
      (by omega) (by omega) hj
    omega
  · -- Backward: a^(j+1) b^(i+1) ∉ L → a^(i+1) b^(i+1) ∈ L
    intro _
    exact anbn_in_lang (i + 1)

-- ===== Helper: pigeonhole principle for Fin n =====

-- We need a simple pigeonhole: if we have n+1 elements mapping to Fin n,
-- two must collide.

-- First, we need some basic Fin lemmas.

-- Prove by strong induction on n.
-- For n = 0: Fin 0 is empty, so f : Fin 1 → Fin 0 is impossible.
-- For n > 0: ...

-- Actually, let's prove it more directly using a counting/decidability argument.
-- We'll use a recursive approach.

-- Helper: removing an element from Fin (n+1)
-- This is getting complex. Let's try a different approach using Lists and Finsets-like reasoning.

-- Simple approach: prove that any function Fin (n+1) → Fin n has a collision
-- by showing it can't be injective (since card (Fin (n+1)) > card (Fin n)).

-- We'll prove the contrapositive: if f is injective from Fin m to Fin n, then m ≤ n.
-- This can be done by induction.

-- Actually, let's just do it directly for our use case.
-- We need: given f : Fin (n+1) → Fin n, there exist i ≠ j with f i = f j.

-- Let's try a clean induction proof.

theorem fin_injective_bound : ∀ (n : Nat) (f : Fin (n + 1) → Fin n), ∃ (i j : Fin (n + 1)), i ≠ j ∧ f i = f j := by
  intro n
  induction n with
  | zero =>
    intro f
    exact absurd (f ⟨0, by omega⟩).isLt (by omega)
  | succ k ih =>
    intro f
    -- We have f : Fin (k + 2) → Fin (k + 1)
    -- Consider the last element: f ⟨k+1, ...⟩
    let last : Fin (k + 2) := ⟨k + 1, by omega⟩
    let v := f last
    -- Check if any other element maps to v
    by_cases h : ∃ (i : Fin (k + 2)), i ≠ last ∧ f i = v
    · obtain ⟨i, hi_ne, hi_eq⟩ := h
      exact ⟨i, last, hi_ne, by rw [hi_eq]⟩
    · push_neg at h
      -- No other element maps to v, so f restricted to Fin (k+1) avoids v
      -- and maps to Fin (k+1) \ {v}, which has k elements ≅ Fin k
      -- Define g : Fin (k+1) → Fin k by "skipping" v
      let embed : Fin (k + 1) → Fin (k + 2) := fun i => ⟨i.val, by omega⟩
      have embed_ne_last : ∀ i : Fin (k + 1), embed i ≠ last := by
        intro i
        simp only [last, embed]
        intro heq
        have := Fin.val_eq_of_eq heq
        simp at this
        omega
      have f_ne_v : ∀ i : Fin (k + 1), f (embed i) ≠ v := by
        intro i
        exact h (embed i) (embed_ne_last i)
      -- Define g : Fin (k+1) → Fin k by removing v from the codomain
      let g : Fin (k + 1) → Fin k := fun i =>
        let fi := f (embed i)
        if hlt : fi.val < v.val then
          ⟨fi.val, by omega⟩
        else
          ⟨fi.val - 1, by
            have hne : fi ≠ v := f_ne_v i
            have hfi_bound := fi.isLt
            have : fi.val ≠ v.val := fun heq => hne (Fin.ext heq)
            omega⟩
      obtain ⟨a, b, hab, hgab⟩ := ih g
      -- Lift back
      use embed a, embed b
      constructor
      · intro heq
        have := Fin.val_eq_of_eq heq
        simp [embed] at this
        exact hab (Fin.ext this)
      · -- f (embed a) = f (embed b)
        -- From g a = g b, we can deduce f (embed a) = f (embed b)
        simp only [g] at hgab
        set fa := f (embed a)
        set fb := f (embed b)
        have hfa_ne_v := f_ne_v a
        have hfb_ne_v := f_ne_v b
        by_cases ha : fa.val < v.val <;> by_cases hb : fb.val < v.val
        · simp [ha, hb] at hgab
          exact Fin.ext hgab
        · simp [ha, hb] at hgab
          have hgab_val := Fin.val_eq_of_eq hgab
          simp at hgab_val
          have : fb.val ≠ v.val := fun heq => hfb_ne_v (Fin.ext heq)
          omega
        · simp [ha, hb] at hgab
          have hgab_val := Fin.val_eq_of_eq hgab
          simp at hgab_val
          have : fa.val ≠ v.val := fun heq => hfa_ne_v (Fin.ext heq)
          omega
        · simp [ha, hb] at hgab
          have hgab_val := Fin.val_eq_of_eq hgab
          simp at hgab_val
          have : fa.val ≠ v.val := fun heq => hfa_ne_v (Fin.ext heq)
          have : fb.val ≠ v.val := fun heq => hfb_ne_v (Fin.ext heq)
          exact Fin.ext (by omega)

-- ===== Main theorem: L is not regular =====

/-- The language generated by S → SaSb | ε | A, A → bb | aa | bSb is not regular. -/
theorem not_regular : ¬ IsRegular (Alpha := Alpha) languagePred := by
  intro ⟨n, M, hM⟩
  -- Handle n = 0 separately
  by_cases hn : n = 0
  · subst hn
    -- Fin 0 is empty, so M.start : Fin 0 is impossible
    exact Fin.elim0 M.start
  · -- n ≥ 1
    -- Consider the n+1 words: words 0, words 1, ..., words n
    -- They map to states in Fin n under M.run
    have hn_pos : n ≥ 1 := Nat.pos_of_ne_zero hn
    let f : Fin (n + 1) → Fin n := fun k => M.run (words k.val)
    obtain ⟨i, j, hij, hfij⟩ := fin_injective_bound n f
    -- words i.val and words j.val reach the same state
    -- So for any suffix z, M.accepts (words i.val ++ z) = M.accepts (words j.val ++ z)
    have same_accept : ∀ z : List Alpha,
        M.accepts (words i.val ++ z) = M.accepts (words j.val ++ z) := by
      intro z
      simp only [DFA.accepts, DFA.run, List.foldl_append]
      show M.accept (List.foldl M.step (List.foldl M.step M.start (words (↑i))) z) =
           M.accept (List.foldl M.step (List.foldl M.step M.start (words (↑j))) z)
      have : f i = f j := hfij
      simp only [f, DFA.run] at this
      rw [this]
    -- But pairwise_distinct gives a suffix z that distinguishes them
    have hne : i.val ≠ j.val := by
      intro heq; exact hij (Fin.ext heq)
    obtain ⟨z, hz⟩ := pairwise_distinct i.val j.val hne
    -- M agrees on both, but the language disagrees — contradiction
    have ha1 := (hM (words i.val ++ z))
    have ha2 := (hM (words j.val ++ z))
    have hsame := same_accept z
    -- Case split on whether words i ++ z ∈ L
    by_cases h : languagePred (words i.val ++ z)
    · -- words i ++ z ∈ L, so M accepts it
      have hMi : M.accepts (words i.val ++ z) = true := ha1.mpr h
      -- By same_accept, M also accepts words j ++ z
      have hMj : M.accepts (words j.val ++ z) = true := by rw [← hsame]; exact hMi
      -- So words j ++ z ∈ L
      have hjL : languagePred (words j.val ++ z) := ha2.mp hMj
      -- But hz says words i ++ z ∈ L → words j ++ z ∉ L
      exact (hz.mp h) hjL
    · -- words i ++ z ∉ L
      -- hz : languagePred (words i ++ z) ↔ ¬ languagePred (words j ++ z)
      -- So ¬ languagePred (words i ++ z) means ¬¬ languagePred (words j ++ z)
      have hjL : languagePred (words j.val ++ z) := by
        by_contra hnj
        exact h (hz.mpr hnj)
      -- So M accepts words j ++ z
      have hMj : M.accepts (words j.val ++ z) = true := ha2.mpr hjL
      -- By same_accept, M accepts words i ++ z
      have hMi : M.accepts (words i.val ++ z) = true := by rw [hsame]; exact hMj
      -- So words i ++ z ∈ L
      exact h (ha1.mp hMi)