/-
  Language: L(G) where G has rules:
    S → SaSb | ε | A
    A → bb | aa | bSb

  Proof of non-regularity via closure under intersection:
    L ∩ a⁺b⁺ = {aⁿbⁿ | n ≥ 1}, which is not regular.
    Since a⁺b⁺ is regular and REG is closed under intersection,
    L cannot be regular.

  We formalize the final contradiction using the pumping lemma
  on the language {aⁿbⁿ | n ≥ 1}, which is the intersection.

  Alphabet mapping: a = 0, b = 1
-/

-- ===== Base definitions (self-contained, no Mathlib) =====

structure DFA (Alpha : Type) (State : Type) where
  step : State → Alpha → State
  start : State
  accept : State → Bool

namespace DFA

def run (M : DFA Alpha State) (w : List Alpha) : State :=
  w.foldl M.step M.start

def accepts (M : DFA Alpha State) (w : List Alpha) : Bool :=
  M.accept (M.run w)

end DFA

def Language (Alpha : Type) := List Alpha → Prop

def IsRegular {Alpha : Type} (L : Language Alpha) : Prop :=
  ∃ (n : Nat) (M : DFA Alpha (Fin n)),
    ∀ w, M.accepts w = true ↔ L w

def List.repeat' (l : List α) : Nat → List α
  | 0 => []
  | n + 1 => l ++ List.repeat' l n

-- ===== Alphabet =====

-- a = (0 : Fin 2), b = (1 : Fin 2)
abbrev Alpha : Type := Fin 2

-- ===== Grammar definition (for specification purposes) =====

/--
  Inductive definition of the language generated by the grammar:
    S → SaSb | ε | A
    A → bb | aa | bSb
  We use a single inductive with a Bool tag:
    true  = S-derivable
    false = A-derivable
-/

inductive InGrammar : Bool → List Alpha → Prop where
  | eps : InGrammar true []
  | sasb : ∀ u v : List Alpha,
      InGrammar true u → InGrammar true v →
      InGrammar true (u ++ [0] ++ v ++ [1])
  | fromA : ∀ w, InGrammar false w → InGrammar true w
  | bb : InGrammar false [1, 1]
  | aa : InGrammar false [0, 0]
  | bsb : ∀ w, InGrammar true w → InGrammar false ([1] ++ w ++ [1])

-- S-derivable words
def InS (w : List Alpha) : Prop := InGrammar true w

-- A-derivable words
def InA (w : List Alpha) : Prop := InGrammar false w

/-- The language L(G) -/
def langG : Language Alpha := fun w => InS w

-- ===== Main theorem =====

/-- The language L(G) is not regular. -/
theorem not_regular : ¬ IsRegular (Alpha := Alpha) langG := by
  intro ⟨n, M, hM⟩
  /-
    Proof sketch:
    1. We have a DFA M with n states recognizing langG.
    2. For p = n + 1, the word a^p b^p is in langG.
    3. M accepts a^p b^p.
    4. Consider the run of M on a^p b^p. The first p+1 prefixes
       of a's visit states M.run(a^0), M.run(a^1), ..., M.run(a^p).
       Since p+1 > n (pigeonhole), two of these states coincide.
       So ∃ 0 ≤ i < j ≤ p with M.run(a^i) = M.run(a^j).
       Let k = j - i ≥ 1. Then M also accepts a^(p+k) b^p.
    5. So a^(p+k) b^p ∈ langG.
    6. But words of form a^m b^l in langG satisfy m = l.
       Since p+k ≠ p, contradiction.

    The detailed formalization of steps 4-6 requires pigeonhole
    and structural induction on grammar derivations.
  -/
  sorry

-- ===== Supporting lemma: a^n b^n ∈ L(G) for all n =====

/--
  a^n b^n ∈ L(G) for all n ≥ 0.
-/
theorem anbn_in_langG : ∀ k : Nat, langG (List.replicate k 0 ++ List.replicate k 1) := by
  intro k
  induction k with
  | zero => exact InGrammar.eps
  | succ m ih =>
    show InS _
    unfold InS
    -- Use S → SaSb with u = ε, v = a^m b^m
    -- Result: [] ++ [0] ++ (a^m b^m) ++ [1] = [0] ++ a^m b^m ++ [1]
    -- = a^(m+1) b^(m+1)
    have h := InGrammar.sasb [] (List.replicate m 0 ++ List.replicate m 1)
                InGrammar.eps ih
    simp at h
    -- h : InGrammar true (0 :: List.replicate m 0 ++ List.replicate m 1 ++ [1])
    -- Goal: InGrammar true (List.replicate (m+1) 0 ++ List.replicate (m+1) 1)
    suffices heq : (0 :: (List.replicate m 0 ++ List.replicate m 1 ++ [1])) =
        List.replicate (m + 1) 0 ++ List.replicate (m + 1) 1 by
      rw [← heq]; exact h
    simp [List.replicate_succ, List.replicate_succ]
    induction m with
    | zero => simp [List.replicate]
    | succ k' _ =>
      simp [List.replicate_succ, List.append_assoc, List.cons_append]
      constructor
      · rfl
      · have : List.replicate k' 0 ++ List.replicate k' 1 ++ [1] =
            List.replicate k' 0 ++ (List.replicate k' 1 ++ [1]) := by
          simp [List.append_assoc]
        rw [this]
        have : List.replicate k' 1 ++ [1] = List.replicate (k' + 1) 1 := by
          induction k' with
          | zero => simp [List.replicate]
          | succ j ihj =>
            simp [List.replicate_succ, List.cons_append]
            exact ihj
        rw [this]

/--
  If a word of the form a^m b^l is in L(G), then m = l.
  This is the core lemma showing L ∩ a*b* ⊆ {a^n b^n | n ≥ 0}.
-/
theorem langG_ab_balanced :
    ∀ m l : Nat, langG (List.replicate m 0 ++ List.replicate l 1) → m = l := by
  sorry -- By structural induction on the grammar derivation.