"""LLM integration for language analysis."""

from .client import LLMClient
from .prompts import (
    SYSTEM_PROMPT,
    PARSE_LANGUAGE_PROMPT,
    SUGGEST_PROOF_STRATEGY_PROMPT,
    SUGGEST_REGULAR_INTERSECTIONS_PROMPT,
    NEURAL_SYMBOLIC_STRATEGY_PROMPT,
    EXPLAIN_RESULT_PROMPT,
)

__all__ = [
    "LLMClient",
    "SYSTEM_PROMPT",
    "PARSE_LANGUAGE_PROMPT",
    "SUGGEST_PROOF_STRATEGY_PROMPT",
    "SUGGEST_REGULAR_INTERSECTIONS_PROMPT",
    "NEURAL_SYMBOLIC_STRATEGY_PROMPT",
    "EXPLAIN_RESULT_PROMPT",
]
