"""Deterministic IR -> Lean 4 *statement* translator (docs/VERDICT_POLICY.md R-Lean).

R-Lean requires that the theorem's **formulation** (alphabet type, language
definition, the claim itself) is generated by code from the task IR, never by
the LLM -- only the proof *body* is LLM-written. This module is that code.
It never calls an LLM, never raises on malformed input (mirrors
``cfl_system.lib.exponent_pattern``'s "return ``None``, don't guess"
convention), and is a pure function of its input: the same IR always
produces byte-identical Lean text.

Public entry point
-------------------
``render_statement(ir, direction) -> LeanStatement | None``. ``direction`` is
one of the seven literal verdict/pipeline tags the four systems' verdict
gates use: ``"regular"``/``"non_regular"`` (agent_system), ``"cfl"``/
``"non_cfl"`` (cfl_system), ``"dcfl"``/``"non_dcfl"`` (dcfl_system), or
``"ll"`` (ll_system -- LL(k) is never formalized; see below). ``None`` means
"this IR/direction cannot be formalized deterministically"; use
``render_statement_verbose`` to also get the reason.

This module handles the **regular** direction's IR kinds (``grammar``,
``regex``, and a *minimal* subset of ``natural``'s exponent notation -- see
below) plus every piece the other three systems' wrapper modules reuse:
``LeanStatement``, ``alphabet_decl``, ``grammar_decl``, ``parse_regex`` and
``pattern_body`` (the exponent-notation segments/condition -> Lean
converter). ``cfl_system.lib.lean_ir`` and ``dcfl_system.lib.lean_ir`` import
these and add their own directions' predicate and (for cfl) the *full*
exponent-notation parser. They cannot live here: root ``CLAUDE.md``'s
"Import direction" is ``agent_system`` -> nothing, ``cfl_system`` ->
``agent_system``, ``dcfl_system``/``ll_system`` -> both, never the reverse --
so this module cannot import ``cfl_system.lib.exponent_pattern``. Its own
``natural``-kind handling (``_parse_simple_exponent_natural``) is therefore a
small, self-contained subset of that module's grammar (whitespace-separated
``letter^var`` blocks, an optional flat ``| a OP b (and/or ...)*`` condition,
no unions, no arithmetic beyond a bare variable/literal, no multi-letter
units) -- enough for ``agent_system``'s own examples (e.g. ``{a^n b^n | n >=
0}``, reg-01). ``cfl_system.lib.lean_ir`` uses the real, general parser
(``cfl_system.lib.exponent_pattern.parse_exponent_pattern``) for its own
``natural``-kind IRs (unions, richer arithmetic, multi-letter units), feeding
its result into this module's ``pattern_body`` -- so the segments/condition
-> Lean *conversion* logic itself is never duplicated, only the small text
parser is (mirrors the existing precedent of ``dcfl_system.lib.dpda`` keeping
its own field-name convention rather than importing ``cfl_system``'s).

Alphabet type
-------------
``inductive Letter | a | b | c ... deriving DecidableEq, Repr`` -- one named
constructor per letter of ``ir.alphabet`` (or ``language_spec``'s
``terminals``/``alphabet`` field, per IR kind), rather than ``Fin k``.
Reasoning: every generated word literal and grammar rule reads as
``Letter.a``/``Letter.b`` instead of an opaque ``(0 : Fin k)``/``(1 : Fin k)``,
which matters because this text is read by both the LLM formalizer (writing
the proof body against these exact names) and a human auditing a `verified`
result. ``Fin k`` would need the same "letter -> index" bookkeeping duplicated
by every reader; a named inductive puts it in one place (this module) and
erases it from everything downstream. Named ``Letter``, not ``Sym``: Mathlib
already has a top-level ``def Sym (α : Type*) (n : ℕ) := ...`` (symmetric
powers, ``Mathlib.Data.Sym.Basic``, transitively imported by every direction
here) -- ``inductive Sym`` in ``check.lean`` collides with it
("`Sym` has already been declared"), confirmed against the pinned image
(``docker run tfl-lean4``) while writing this module.

``deriving DecidableEq, Repr`` only, **not** ``Fintype``, on the ``Letter``
inductive itself: ``deriving Fintype`` for a plain enum inductive fails to
elaborate under the pinned toolchain, ``leanprover/lean4:v4.33.0``
(confirmed with a minimal ``inductive Letter | a | b deriving Fintype``
against ``docker run tfl-lean4``: `` Tactic `rewrite` failed... Application
type mismatch: ... Letter.enumList_nodup ... expected ...
(↑Letter.enumList).Nodup`` -- a `Finset`/`Multiset` coercion mismatch
inside the derive handler itself, not anything to do with this module's
generated names -- and the hint Lean prints for the error,
``deriving instance Fintype for Letter`` as a separate command, hits the
exact same broken handler). Every ``LeanStatement`` this module or its
``cfl_system``/``dcfl_system`` wrappers ever produced with ``Fintype`` in
the ``deriving`` clause would have failed to type-check regardless of the
proof body.

Whether a ``Fintype Letter`` instance is needed at all depends on the
direction: ``Language.IsRegular``/``Language.IsContextFree``
(``Mathlib.Computability.{DFA, ContextFreeGrammar}``) quantify ``Fintype``
over the automaton's *state* type only, never over the alphabet -- REG/CFL
statements need nothing beyond ``DecidableEq Letter``. langlib's
``is_DCF``/``is_DPDA`` (``Langlib/Automata/DeterministicPushdown/
Definition.lean``: ``is_DPDA {T : Type} [Fintype T] (L : Language T) :
Prop``) is the opposite: it takes ``[Fintype T]`` on the alphabet as an
explicit instance argument, so a DCFL statement genuinely cannot elaborate
without one (confirmed: ``dcfl_system.lib.lean_ir``'s statements fail
``failed to synthesize instance ... Fintype Letter`` against ``docker run
tfl-lean4`` without it). ``fintype_instance_decl(sym_map)`` is the
workaround: a literal ``Finset`` of every constructor plus a ``decide``d
completeness proof (``instance : Fintype Letter where elems := {Letter.a,
...}; complete := by intro x; cases x <;> decide``), which *does* compile
-- ``dcfl_system.lib.lean_ir`` appends it after ``alphabet_decl`` for both
its directions; ``agent_system.lib.lean_ir``/``cfl_system.lib.lean_ir``
never call it, since REG/CFL statements don't need it and it would just be
dead code in their generated files.

CFL/DCFL predicate provenance
------------------------------
Checked directly against the pinned toolchain (``agent_system/docker/tfl_lean``,
``leanprover/lean4:v4.33.0`` + Mathlib, ``lake exe cache get`` already warms
the *whole* Mathlib .olean cache, confirmed via ``docker run tfl-lean4`` while
writing this module) and against a read-only reference clone of ``langlib``
(commit ``c5fb8340b42543713f79e1c283a3f6a929cb71ef``, ``lean-toolchain``
v4.33.0) kept outside the repo for the duration of this work -- it is
reference-only, never imported at runtime and not wired into any test's
lookup path; grep it directly (``Langlib/Classes/...``) when re-checking a
predicate/lemma name below:

- **REG**: Mathlib's own ``Language.IsRegular`` (``Mathlib.Computability.Language``,
  transitively available once ``Mathlib.Computability.RegularExpressions``
  is imported, which ``TflLean`` already does) -- langlib's own regularity
  class (``is_RG``, ``Langlib/Grammars/RightRegular/Definition.lean``) is a
  *different*, grammar-shaped definition its examples don't actually use for
  proofs (``Langlib/Classes/Regular/Examples/AnBn.lean`` proves
  ``anbn_not_isRegular : ¬ anbn.IsRegular`` directly against Mathlib's
  predicate via ``Language.isRegular_iff_finite_range_leftQuotient``).
- **CFL**: Mathlib's own ``Language.IsContextFree`` (``∃ g : ContextFreeGrammar
  T, g.language = L`` -- ``Mathlib.Computability.ContextFreeGrammar``), *not*
  langlib's own ``is_CF`` (``Langlib/Classes/ContextFree/Definition.lean``,
  built over langlib's separate unrestricted-``grammar`` type). The two are
  proved equivalent by langlib itself (``is_CF_iff_isContextFree``), and
  critically langlib proves its pumping lemma and Ogden's lemma **directly
  in Mathlib's own namespace**: ``Language.IsContextFree.pumping``
  (``Langlib/Classes/ContextFree/Pumping/Pumping.lean``) and
  ``Language.IsContextFree.ogdens_lemma``
  (``Langlib/Classes/ContextFree/Basics/Ogden.lean``) -- so
  ``Language.IsContextFree`` is "the one with the pumping lemma" the task
  asked to identify, while also being the Mathlib-native predicate that only
  needs ``import Mathlib.Computability.ContextFreeGrammar`` to *state* (no
  langlib dependency for the statement itself, only for a ``non_cfl`` proof
  body that cites the pumping/Ogden lemmas).
- **DCFL**: Mathlib has no deterministic-pushdown-automaton formalization at
  all (``grep``ped ``Mathlib/Computability/`` while writing this module: no
  hit), so the DCFL direction uses langlib's own ``is_DCF``
  (``Langlib/Classes/DeterministicContextFree/Definition.lean``:
  ``is_DCF (L : Language T) : Prop := is_DPDA L``, over langlib's own DPDA
  automaton type) -- there is no alternative.
- **langlib availability**: ``agent_system/docker/tfl_lean/lakefile.toml``
  now pins ``langlib`` as a Lake dependency (``rev
  c5fb8340b42543713f79e1c283a3f6a929cb71ef``, matching the reference clone
  above) and the pinned ``tfl-lean4`` image has it built in
  (``docker run tfl-lean4 ls .lake/packages/`` lists ``langlib`` alongside
  ``mathlib``, confirmed while writing this module) -- so, as of this
  module, statements for every direction (including ``cfl``/``non_cfl``/
  ``dcfl``/``non_dcfl`` with their real ``Langlib.Classes...`` imports, not
  a stripped-imports substitute) actually type-check against the current
  image; ``cfl_system.lib.lean_ir``'s and ``dcfl_system.lib.lean_ir``'s own
  Docker-conditional tests exercise this directly.

LL(k)
-----
Always ``None`` (``direction == "ll"``): LL(k)-ness is a property of a
*grammar*'s parsing algorithm, not of the language it generates, so "is this
language LL(k)" isn't even a well-formed Mathlib/langlib statement the way
regularity/CFL-ness/DCFL-ness are (see docs/VERDICT_POLICY.md R-Lean: "LL(k)
— не формализуется").

Language construction
----------------------
- ``grammar`` kind -> Mathlib ``ContextFreeGrammar Letter`` (``g``) with
  ``L := g.language`` (used for all three of reg/cfl/dcfl -- e.g. dcfl's
  exam_04, ``task_grammar_aSSb``, is a grammar IR).
- ``regex`` kind (``has_backreferences: false`` only -- ``true`` means the
  pattern isn't a regular expression at all and is rejected with a reason)
  -> Mathlib ``RegularExpression Letter`` (``re``) with ``L := re.matches'``.
  Supports literal alphabet characters, ``|`` (union), implicit
  concatenation, ``*``/``+``/``?`` (postfix repetition/optional) and ``()``
  grouping -- i.e. plain regular-expression syntax, nothing POSIX-specific
  (no character classes, no anchors, no backreferences).
- ``natural`` kind with exponent notation -- ``{a^n b^n c^m | ...}`` style --
  via ``List.replicate``/(for multi-letter units) ``List.replicate ... .flatten``
  segments existentially quantified over ℕ, `w = <segments>`` conjoined with
  the (optional) condition. A word this shape describes needn't be
  "resolvable" the way ``cfl_system.lib.exponent_pattern``'s runtime *oracle*
  needs to be (see that module's docstring) -- a Lean ``Prop`` is just an
  existentially-quantified equation, not an algorithm, so this module
  supports strictly more IR than that module's ``accepts()`` can decide.
  What it does *not* support: ``-`` (unbounded ℕ subtraction would silently
  change the meaning) anywhere in an exponent expression.
- ``natural`` kind describing a palindrome (``w = reverse(w)`` / ``w = w^R`` /
  ``w = wᴿ``, case-insensitively) -> ``L := {w : List Letter | w = w.reverse}``.
- Anything else (``predicate``, ``arithmetic_index``, cfl's
  ``grammar_filter``/``repeated_subword``/``exists_decomposition``, a
  ``natural`` description that is neither exponent notation nor a simple
  palindrome, a dcfl ``set_builder`` that isn't the letter-domain shape
  ``cfl_system/lib/lean_ir.py`` and ``dcfl_system/lib/lean_ir.py`` handle) ->
  ``None`` with a reason. This module never invents a formalization for
  something it cannot mechanically translate.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

__all__ = [
    "LeanStatement",
    "alphabet_decl",
    "fintype_instance_decl",
    "grammar_decl",
    "parse_regex",
    "pattern_body",
    "render_statement",
    "render_statement_verbose",
]

# ---------------------------------------------------------------------------
# LeanStatement
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LeanStatement:
    """A deterministically-generated Lean 4 theorem formulation.

    ``alphabet_decl``: the ``inductive Letter ...`` declaration.
    ``language_decl``: whatever else the statement needs (grammar/regex/`NT`
      declarations and ``def L : Language Letter := ...``).
    ``theorem_decl``: ``"theorem tfl_main : <Prop>"`` -- no ``:= by ...``;
      :meth:`render` appends that with the harness-supplied proof body.
    ``imports``: full ``import ...`` lines, in the order they should appear,
      always starting with ``"import TflLean"``.
    ``name``: the theorem's name (``"tfl_main"`` -- R-Lean's fixed contract).
    """

    alphabet_decl: str
    language_decl: str
    theorem_decl: str
    imports: list[str] = field(default_factory=list)
    name: str = "tfl_main"

    def render(self, proof: str = "sorry") -> str:
        """Assemble the full ``.lean`` file text, substituting *proof* into
        the ``:= by`` block. The harness substitutes the formalizer LLM's
        proof body here; the default ``"sorry"`` is what the Docker-conditional
        syntax-only test in ``agent_system/tests/test_lean_ir.py`` compiles."""
        parts = list(self.imports)
        parts.append("")
        parts.append(self.alphabet_decl)
        parts.append("")
        parts.append(self.language_decl)
        parts.append("")
        parts.append(f"{self.theorem_decl} := by\n  {proof}")
        return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Identifiers
# ---------------------------------------------------------------------------

_LEAN_KEYWORDS = {
    "let", "fun", "match", "with", "do", "if", "then", "else", "by", "from",
    "have", "show", "theorem", "def", "inductive", "structure", "class",
    "instance", "import", "open", "namespace", "end", "variable", "variables",
    "where", "deriving", "this", "sorry", "Type", "Prop", "Sort", "forall",
    "exists", "in", "at", "calc", "suffices", "assume", "set_option",
    "section", "mut", "rec", "macro", "syntax", "notation", "attribute",
}
_IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def _safe_ident(raw: str, fallback_prefix: str, idx: int, used: set[str]) -> str:
    """A valid, unused Lean identifier for *raw* (a single IR token -- an
    alphabet letter or a nonterminal name), reusing *raw* verbatim when it
    already is one and isn't a keyword, else falling back to
    ``f"{fallback_prefix}{idx}"``, de-duplicated against *used* (mutated)."""
    cand = raw if (isinstance(raw, str) and _IDENT_RE.fullmatch(raw) and raw not in _LEAN_KEYWORDS) else None
    if cand is None:
        cand = f"{fallback_prefix}{idx}"
    base = cand
    n = 1
    while cand in used:
        cand = f"{base}_{n}"
        n += 1
    used.add(cand)
    return cand


def alphabet_decl(symbols: list) -> tuple[str, dict[str, str]] | None:
    """``inductive Letter | <ctor> | ... deriving DecidableEq, Repr`` (not
    ``Fintype`` -- see the module docstring's "Alphabet type" section) for
    the (order-preserving, de-duplicated) *symbols*, plus the
    ``{original symbol: Lean constructor name}`` map. ``None`` if *symbols*
    isn't a non-empty list of non-empty strings."""
    if not isinstance(symbols, list):
        return None
    seen: list[str] = []
    for s in symbols:
        if not isinstance(s, str) or not s:
            return None
        if s not in seen:
            seen.append(s)
    if not seen:
        return None
    used: set[str] = set()
    mapping: dict[str, str] = {}
    for i, s in enumerate(seen):
        mapping[s] = _safe_ident(s, "t", i, used)
    ctor_list = " | ".join(mapping[s] for s in seen)
    decl = (
        "inductive Letter\n"
        f"  | {ctor_list}\n"
        "  deriving DecidableEq, Repr"
    )
    return decl, mapping


def fintype_instance_decl(sym_map: dict[str, str]) -> str | None:
    """A hand-written ``instance : Fintype Letter where ...`` for the
    ``Letter`` inductive *sym_map* (``alphabet_decl``'s second return value)
    names -- for statements that actually need ``Fintype Letter`` (langlib's
    ``is_DPDA``/``is_DCF`` do, via ``DPDA``'s ``[Fintype T]`` -- confirmed
    against ``docker run tfl-lean4``: ``dcfl_system.lib.lean_ir``'s
    statements fail with ``failed to synthesize instance ... Fintype
    Letter`` without this. ``Language.IsRegular``/``Language.IsContextFree``
    do not, see the module docstring's "Alphabet type" section, so
    ``agent_system.lib.lean_ir``/``cfl_system.lib.lean_ir`` never call this).

    Deliberately **not** ``deriving Fintype`` (broken on the pinned
    toolchain for a plain enum inductive, see "Alphabet type" above) or the
    hint-suggested standalone ``deriving instance Fintype for Letter``
    (same derive handler, same failure) -- a literal ``Finset`` of every
    constructor plus a ``decide``d completeness proof, which *does* compile
    (confirmed against ``docker run tfl-lean4`` while writing this module).
    ``None`` if *sym_map* is empty (mirrors ``alphabet_decl``, which never
    itself returns an empty mapping, but this function stays a pure,
    independently-callable sibling)."""
    if not sym_map:
        return None
    elems = "{" + ", ".join(f"Letter.{ctor}" for ctor in sym_map.values()) + "}"
    return (
        "instance : Fintype Letter where\n"
        f"  elems := {elems}\n"
        "  complete := by intro x; cases x <;> decide"
    )


# ---------------------------------------------------------------------------
# Grammar -> Mathlib ContextFreeGrammar
# ---------------------------------------------------------------------------


def grammar_decl(lang_spec: dict, sym_map: dict[str, str]) -> str | None:
    """``inductive NT ...`` + ``def g : ContextFreeGrammar Letter := ...`` +
    ``def L : Language Letter := g.language`` for a ``kind == "grammar"``
    ``language_spec`` (``nonterminals``, ``start``, ``rules: [{lhs, rhs}]``).
    Every ``rhs`` token must be a member of *sym_map* (a terminal) or of
    ``nonterminals``; ``None`` on any other malformed/unsupported shape."""
    if not isinstance(lang_spec, dict):
        return None
    nonterminals = lang_spec.get("nonterminals")
    start = lang_spec.get("start")
    rules = lang_spec.get("rules")
    if not (isinstance(nonterminals, list) and isinstance(start, str) and isinstance(rules, list)):
        return None
    if not nonterminals or start not in nonterminals:
        return None

    seen_nt: list[str] = []
    for n in nonterminals:
        if not isinstance(n, str) or not n:
            return None
        if n not in seen_nt:
            seen_nt.append(n)

    used: set[str] = set()
    nt_map: dict[str, str] = {}
    for i, n in enumerate(seen_nt):
        nt_map[n] = _safe_ident(n, "N", i, used)

    rule_texts: list[str] = []
    for rule in rules:
        if not isinstance(rule, dict):
            return None
        lhs = rule.get("lhs")
        rhs = rule.get("rhs")
        if lhs not in nt_map or not isinstance(rhs, list):
            return None
        sym_texts: list[str] = []
        for tok in rhs:
            if tok in nt_map:
                sym_texts.append(f"Symbol.nonterminal NT.{nt_map[tok]}")
            elif tok in sym_map:
                sym_texts.append(f"Symbol.terminal Letter.{sym_map[tok]}")
            else:
                return None
        rule_texts.append(f"⟨NT.{nt_map[lhs]}, [{', '.join(sym_texts)}]⟩")

    nt_ctor_list = " | ".join(nt_map[n] for n in seen_nt)
    nt_decl = f"inductive NT\n  | {nt_ctor_list}\n  deriving DecidableEq, Repr"
    rules_set = "{" + ", ".join(rule_texts) + "}"

    return (
        f"{nt_decl}\n\n"
        "def g : ContextFreeGrammar Letter :=\n"
        f"  {{ NT := NT, initial := NT.{nt_map[start]}, rules := {rules_set} }}\n\n"
        "def L : Language Letter := g.language"
    )


# ---------------------------------------------------------------------------
# Regex -> Mathlib RegularExpression (no backreferences)
# ---------------------------------------------------------------------------


def parse_regex(pattern: str, sym_map: dict[str, str]) -> str | None:
    """A ``RegularExpression Letter`` term for *pattern* (alphabet chars, ``|``,
    implicit concatenation, postfix ``*``/``+``/``?``, ``()`` grouping) --
    ``None`` for anything else (backreferences, character classes, anchors,
    unrecognized characters, or a character outside *sym_map*)."""
    if not isinstance(pattern, str):
        return None
    pos = [0]
    n = len(pattern)

    def peek() -> str | None:
        return pattern[pos[0]] if pos[0] < n else None

    def advance() -> str:
        c = pattern[pos[0]]
        pos[0] += 1
        return c

    def parse_union() -> str | None:
        left = parse_concat()
        if left is None:
            return None
        while peek() == "|":
            advance()
            right = parse_concat()
            if right is None:
                return None
            left = f"({left} + {right})"
        return left

    def parse_concat() -> str | None:
        parts: list[str] = []
        while True:
            c = peek()
            if c is None or c in "|)":
                break
            atom = parse_star()
            if atom is None:
                return None
            parts.append(atom)
        if not parts:
            return "RegularExpression.epsilon"
        expr = parts[0]
        for p in parts[1:]:
            expr = f"({expr} * {p})"
        return expr

    def parse_star() -> str | None:
        atom = parse_atom()
        if atom is None:
            return None
        while peek() in ("*", "+", "?"):
            op = advance()
            if op == "*":
                atom = f"(RegularExpression.star {atom})"
            elif op == "+":
                atom = f"({atom} * RegularExpression.star {atom})"
            else:  # "?"
                atom = f"(RegularExpression.epsilon + {atom})"
        return atom

    def parse_atom() -> str | None:
        c = peek()
        if c is None:
            return None
        if c == "(":
            advance()
            inner = parse_union()
            if inner is None or peek() != ")":
                return None
            advance()
            return inner
        if c in sym_map:
            advance()
            return f"(RegularExpression.char Letter.{sym_map[c]})"
        return None

    result = parse_union()
    if result is None or pos[0] != n:
        return None
    return result


# ---------------------------------------------------------------------------
# Exponent-notation segments/condition -> Lean (shared converter; the parser
# that PRODUCES segments/condition is elsewhere -- see module docstring).
#
# ``segments``: list of ``{"literal": str}`` or ``{"unit": str, "expr": Expr}``.
# ``condition``: ``None`` or a boolean-condition AST node.
# ``Expr``    := ("num", int) | ("var", str) | ("bin", "+"|"*", Expr, Expr)
#                -- NOT "-"/"neg": unbounded truncating subtraction in ℕ
#                would silently change the statement's meaning, so any
#                expression using it is rejected (``None``).
# ``Cond``    := ("chain", [[Expr]], [op]) | ("not", Cond) | ("and"|"or", [Cond])
#                -- exactly cfl_system.lib.exponent_pattern's shapes (its
#                ``ExponentPattern.segments``/``.condition`` fields), so
#                ``cfl_system.lib.lean_ir`` can feed this function that
#                module's *real* parser output directly.
# ---------------------------------------------------------------------------

_REL_LEAN = {"==": "=", "!=": "≠", "<": "<", "<=": "≤", ">": ">", ">=": "≥"}


def _expr_vars(expr: tuple) -> set[str]:
    kind = expr[0]
    if kind == "var":
        return {expr[1]}
    if kind == "bin":
        return _expr_vars(expr[2]) | _expr_vars(expr[3])
    return set()


def _cond_vars(node: tuple) -> set[str]:
    kind = node[0]
    if kind == "chain":
        vs: set[str] = set()
        for group in node[1]:
            for e in group:
                vs |= _expr_vars(e)
        return vs
    if kind == "not":
        return _cond_vars(node[1])
    if kind in ("and", "or"):
        vs = set()
        for n in node[1]:
            vs |= _cond_vars(n)
        return vs
    return set()


def _expr_to_lean(expr: tuple, var_names: dict[str, str]) -> str | None:
    kind = expr[0]
    if kind == "num":
        return str(expr[1])
    if kind == "var":
        return var_names.get(expr[1])
    if kind == "bin":
        _, op, l, r = expr
        if op not in ("+", "*"):
            return None
        ls = _expr_to_lean(l, var_names)
        rs = _expr_to_lean(r, var_names)
        if ls is None or rs is None:
            return None
        return f"({ls} + {rs})" if op == "+" else f"({ls} * {rs})"
    return None


def _cond_to_lean(node: tuple, var_names: dict[str, str]) -> str | None:
    kind = node[0]
    if kind == "chain":
        _, groups, ops = node
        parts: list[str] = []
        for i, op in enumerate(ops):
            lean_op = _REL_LEAN.get(op)
            if lean_op is None:
                return None
            for le in groups[i]:
                for re_ in groups[i + 1]:
                    ls = _expr_to_lean(le, var_names)
                    rs = _expr_to_lean(re_, var_names)
                    if ls is None or rs is None:
                        return None
                    parts.append(f"{ls} {lean_op} {rs}")
        return " ∧ ".join(parts) if parts else None
    if kind == "not":
        inner = _cond_to_lean(node[1], var_names)
        return None if inner is None else f"¬ ({inner})"
    if kind in ("and", "or"):
        parts = [_cond_to_lean(n, var_names) for n in node[1]]
        if any(p is None for p in parts):
            return None
        sep = " ∧ " if kind == "and" else " ∨ "
        return "(" + sep.join(parts) + ")"
    return None


def _segments_to_lean(segments: list[dict], sym_map: dict[str, str], var_names: dict[str, str]) -> str | None:
    parts: list[str] = []
    for seg in segments:
        if "literal" in seg:
            lit = seg["literal"]
            if not lit:
                continue
            if any(ch not in sym_map for ch in lit):
                return None
            parts.append("[" + ", ".join(f"Letter.{sym_map[ch]}" for ch in lit) + "]")
            continue
        unit = seg.get("unit")
        expr = seg.get("expr")
        if not unit or expr is None:
            return None
        count_lean = _expr_to_lean(expr, var_names)
        if count_lean is None:
            return None
        if len(unit) == 1:
            if unit not in sym_map:
                return None
            parts.append(f"List.replicate {count_lean} Letter.{sym_map[unit]}")
        else:
            if any(ch not in sym_map for ch in unit):
                return None
            lit_list = "[" + ", ".join(f"Letter.{sym_map[ch]}" for ch in unit) + "]"
            parts.append(f"(List.replicate {count_lean} {lit_list}).flatten")
    return " ++ ".join(parts) if parts else "[]"


def pattern_body(segments: list[dict], condition: tuple | None, sym_map: dict[str, str]) -> str | None:
    """The set-builder body (without the surrounding ``{w : List Letter | ...}``)
    for one exponent-notation branch: ``∃ <vars> : ℕ, w = <segments> [∧
    <condition>]``, or just ``w = <segments>`` when no variable appears
    anywhere. ``None`` if *segments*/*condition* use anything this converter
    doesn't support (a letter outside *sym_map*, ``-`` in an exponent, an
    unrecognized condition shape)."""
    if not isinstance(segments, list) or not segments:
        return None
    block_vars: set[str] = set()
    for seg in segments:
        if "expr" in seg:
            block_vars |= _expr_vars(seg["expr"])
    cond_vars = _cond_vars(condition) if condition is not None else set()
    all_vars = sorted(block_vars | cond_vars)

    used = {"w"}
    var_names: dict[str, str] = {}
    for v in all_vars:
        ident = v
        while ident in used:
            ident = f"{ident}_"
        var_names[v] = ident
        used.add(ident)

    word_expr = _segments_to_lean(segments, sym_map, var_names)
    if word_expr is None:
        return None

    clauses = [f"w = {word_expr}"]
    if condition is not None:
        cond_text = _cond_to_lean(condition, var_names)
        if cond_text is None:
            return None
        clauses.append(cond_text)
    body = " ∧ ".join(clauses)
    if all_vars:
        quant = " ".join(var_names[v] for v in all_vars)
        return f"∃ {quant} : ℕ, {body}"
    return body


# ---------------------------------------------------------------------------
# agent_system's own minimal exponent-notation parser (natural kind, REG
# direction only) -- see module docstring for why this is a small local
# subset rather than an import of cfl_system.lib.exponent_pattern.
# ---------------------------------------------------------------------------

_BLOCK_TOKEN_RE = re.compile(r"([A-Za-z])\^\{?([A-Za-z])\}?")
_REL_TOKEN_RE = re.compile(r"(==|!=|<=|>=|<|>|=)")
_AND_OR_SPLIT_RE = re.compile(r"\s+(and|or)\s+", re.IGNORECASE)


def _parse_simple_atom(text: str) -> tuple | None:
    text = text.strip()
    if re.fullmatch(r"[0-9]+", text):
        return ("num", int(text))
    if re.fullmatch(r"[A-Za-z]", text):
        return ("var", text)
    return None


def _parse_simple_condition(text: str) -> tuple | None:
    """``v1 OP v2 (and/or v3 OP v4)*`` -- a flat conjunction/disjunction of
    two-sided comparisons between a single variable and/or integer literal;
    no parentheses, no comma chains, no ``not``, no mixed and/or."""
    parts = _AND_OR_SPLIT_RE.split(text)
    clauses = parts[0::2]
    joiners = [p.lower() for p in parts[1::2]]
    if joiners and any(j != joiners[0] for j in joiners):
        return None
    nodes = []
    for clause in clauses:
        m = _REL_TOKEN_RE.search(clause)
        if not m:
            return None
        op = "==" if m.group(1) == "=" else m.group(1)
        left = _parse_simple_atom(clause[: m.start()])
        right = _parse_simple_atom(clause[m.end():])
        if left is None or right is None:
            return None
        nodes.append(("chain", [[left], [right]], [op]))
    if len(nodes) == 1:
        return nodes[0]
    kind = "and" if not joiners or joiners[0] == "and" else "or"
    return (kind, nodes)


def _parse_simple_exponent_natural(text: str) -> tuple[list[dict], tuple | None] | None:
    if not isinstance(text, str):
        return None
    s = text.strip()
    if s.startswith("{") and s.endswith("}"):
        s = s[1:-1].strip()
    pattern_part, sep, cond_part = s.partition("|")
    pattern_part = pattern_part.strip()
    cond_part = cond_part.strip()

    tokens = pattern_part.split()
    if not tokens:
        return None
    segments = []
    for tok in tokens:
        m = _BLOCK_TOKEN_RE.fullmatch(tok)
        if not m:
            return None
        segments.append({"unit": m.group(1), "expr": ("var", m.group(2))})

    condition = None
    if sep:
        if not cond_part:
            return None
        condition = _parse_simple_condition(cond_part)
        if condition is None:
            return None
    return segments, condition


_PALINDROME_RE = re.compile(
    r"""^\s*
        \{?\s*
        (?:[A-Za-z]\s*(?:(?:in|∈)\s*[^|]*?\*\s*)?\|\s*)?
        (?P<var>[A-Za-z])\s*
        (?:
            =\s*reverse\s*\(\s*(?P=var)\s*\)
            |
            =\s*(?P=var)\s*(?:\^\{?R\}?|ᴿ)
            |
            (?:\^\{?R\}?|ᴿ)\s*=\s*(?P=var)
        )
        \s*\}?\s*$
    """,
    re.IGNORECASE | re.VERBOSE,
)


def _palindrome_body(description: str) -> str | None:
    """Recognize *only* a strict "all palindromes" set-builder description
    -- ``{w (in Sigma*)? | w = reverse(w)}`` (or ``w = w^R`` / ``w^R = w``),
    with nothing else in the body -- via ``fullmatch`` against the whole
    (stripped) description.

    A ``search`` here (the previous implementation) would also match e.g.
    ``{w in {a,b}* | w = reverse(w) and |w| is even}`` or
    ``{w | w = w^R, |w|_a = 2}``: additional conditions the description
    imposes beyond "is a palindrome", silently formalizing the wrong
    (larger) language as "the language of all palindromes". Any extra
    clause must instead make this return ``None`` -- the whole point of
    ``fullmatch``.
    """
    if not isinstance(description, str):
        return None
    if _PALINDROME_RE.fullmatch(description.strip()):
        return "w = w.reverse"
    return None


# ---------------------------------------------------------------------------
# render_statement (REG direction; "cfl"/"non_cfl"/"dcfl"/"non_dcfl" delegate
# to cfl_system.lib.lean_ir / dcfl_system.lib.lean_ir)
# ---------------------------------------------------------------------------

_DIRECTIONS_REG = {"regular": False, "non_regular": True}
_ALL_DIRECTIONS = {
    "regular", "non_regular", "cfl", "non_cfl", "dcfl", "non_dcfl", "ll",
}


def render_statement(ir: dict, direction: str) -> LeanStatement | None:
    stmt, _reason = render_statement_verbose(ir, direction)
    return stmt


def render_statement_verbose(ir: dict, direction: str) -> tuple[LeanStatement | None, str | None]:
    """``(LeanStatement, None)`` on success, ``(None, reason)`` otherwise.
    Never raises."""
    try:
        return _render_statement_verbose(ir, direction)
    except Exception as exc:  # pragma: no cover - defensive; never raise
        return None, f"internal error: {exc!r}"


def _render_statement_verbose(ir: dict, direction: str) -> tuple[LeanStatement | None, str | None]:
    if direction == "ll":
        return None, (
            "LL(k)-ness is a property of a grammar's parsing algorithm, not "
            "of the language it generates -- not formalized (docs/VERDICT_"
            "POLICY.md R-Lean: 'LL(k) — не формализуется')"
        )
    if direction not in _ALL_DIRECTIONS:
        return None, f"unknown direction {direction!r}"
    if direction not in _DIRECTIONS_REG:
        return None, (
            f"direction {direction!r} is handled by "
            f"{'cfl_system' if direction in ('cfl', 'non_cfl') else 'dcfl_system'}"
            ".lib.lean_ir, not agent_system.lib.lean_ir"
        )
    if not isinstance(ir, dict):
        return None, "ir must be a dict"
    negate = _DIRECTIONS_REG[direction]

    lang_spec = ir.get("language_spec")
    if not isinstance(lang_spec, dict):
        return None, "ir.language_spec is missing or not an object"
    kind = lang_spec.get("kind")

    if kind == "grammar":
        return _render_grammar_case(lang_spec, negate)
    if kind == "regex":
        return _render_regex_case(ir, lang_spec, negate)
    if kind == "natural":
        return _render_natural_case(ir, lang_spec, negate)
    return None, f"unsupported language_spec.kind {kind!r} for direction {direction!r}"


def _render_grammar_case(lang_spec: dict, negate: bool) -> tuple[LeanStatement | None, str | None]:
    terminals = lang_spec.get("terminals")
    alpha = alphabet_decl(terminals) if isinstance(terminals, list) else None
    if alpha is None:
        return None, "grammar language_spec missing a usable 'terminals' list"
    alpha_decl, sym_map = alpha
    lang_decl = grammar_decl(lang_spec, sym_map)
    if lang_decl is None:
        return None, "grammar language_spec could not be translated (malformed rules or symbols)"
    prop = "L.IsRegular"
    if negate:
        prop = f"¬ {prop}"
    theorem_decl = f"theorem tfl_main : {prop}"
    imports = ["import TflLean", "import Mathlib.Computability.ContextFreeGrammar"]
    return LeanStatement(alpha_decl, lang_decl, theorem_decl, imports), None


def _render_regex_case(ir: dict, lang_spec: dict, negate: bool) -> tuple[LeanStatement | None, str | None]:
    if lang_spec.get("has_backreferences"):
        return None, "regex uses backreferences; not expressible as a Mathlib RegularExpression"
    pattern = lang_spec.get("pattern")
    alphabet = lang_spec.get("alphabet") or ir.get("alphabet")
    if not isinstance(pattern, str):
        return None, "regex language_spec missing 'pattern'"
    alpha = alphabet_decl(alphabet)
    if alpha is None:
        return None, "regex language_spec missing a usable alphabet"
    alpha_decl, sym_map = alpha
    re_expr = parse_regex(pattern, sym_map)
    if re_expr is None:
        return None, (
            f"regex pattern {pattern!r} uses syntax this translator does not "
            "support (only literal alphabet characters, (), |, *, +, ? are)"
        )
    lang_decl = (
        f"def re : RegularExpression Letter := {re_expr}\n\n"
        "def L : Language Letter := re.matches'"
    )
    prop = "L.IsRegular"
    if negate:
        prop = f"¬ {prop}"
    theorem_decl = f"theorem tfl_main : {prop}"
    return LeanStatement(alpha_decl, lang_decl, theorem_decl, ["import TflLean"]), None


def _render_natural_case(ir: dict, lang_spec: dict, negate: bool) -> tuple[LeanStatement | None, str | None]:
    description = lang_spec.get("description")
    alphabet = ir.get("alphabet") or lang_spec.get("alphabet")
    if not isinstance(description, str):
        return None, "natural language_spec missing 'description'"
    alpha = alphabet_decl(alphabet)
    if alpha is None:
        return None, "no usable alphabet declared in IR for a 'natural' language_spec"
    alpha_decl, sym_map = alpha

    parsed = _parse_simple_exponent_natural(description)
    body = None
    if parsed is not None:
        segments, condition = parsed
        body = pattern_body(segments, condition, sym_map)
    if body is None:
        body = _palindrome_body(description)
    if body is None:
        return None, (
            "natural-language description is neither simple exponent "
            "notation (whitespace-separated letter^var blocks) nor a "
            "recognized w = reverse(w) palindrome description -- "
            "cfl_system.lib.lean_ir's full exponent-notation parser may "
            "still handle it for the cfl/dcfl directions"
        )
    lang_decl = f"def L : Language Letter := {{w : List Letter | {body}}}"
    prop = "L.IsRegular"
    if negate:
        prop = f"¬ {prop}"
    theorem_decl = f"theorem tfl_main : {prop}"
    return LeanStatement(alpha_decl, lang_decl, theorem_decl, ["import TflLean"]), None
