"""Deterministic IR -> Lean 4 *statement* translator (docs/VERDICT_POLICY.md R-Lean).

R-Lean requires that the theorem's **formulation** (alphabet type, language
definition, the claim itself) is generated by code from the task IR, never by
the LLM -- only the proof *body* is LLM-written. This module is that code.
It never calls an LLM, never raises on malformed input (mirrors
``cfl_system.lib.exponent_pattern``'s "return ``None``, don't guess"
convention), and is a pure function of its input: the same IR always
produces byte-identical Lean text.

Public entry point
-------------------
``render_statement(ir, direction) -> LeanStatement | None``. ``direction`` is
one of the seven literal verdict/pipeline tags the four systems' verdict
gates use: ``"regular"``/``"non_regular"`` (agent_system), ``"cfl"``/
``"non_cfl"`` (cfl_system), ``"dcfl"``/``"non_dcfl"`` (dcfl_system), or
``"ll"`` (ll_system -- LL(k) is never formalized; see below). ``None`` means
"this IR/direction cannot be formalized deterministically"; use
``render_statement_verbose`` to also get the reason.

This module handles the **regular** direction's IR kinds (``grammar``,
``regex``, and a *minimal* subset of ``natural``'s exponent notation -- see
below) plus every piece the other three systems' wrapper modules reuse:
``LeanStatement``, ``alphabet_decl``, ``grammar_decl``, ``parse_regex`` and
``pattern_body`` (the exponent-notation segments/condition -> Lean
converter). ``cfl_system.lib.lean_ir`` and ``dcfl_system.lib.lean_ir`` import
these and add their own directions' predicate and (for cfl) the *full*
exponent-notation parser. They cannot live here: root ``CLAUDE.md``'s
"Import direction" is ``agent_system`` -> nothing, ``cfl_system`` ->
``agent_system``, ``dcfl_system``/``ll_system`` -> both, never the reverse --
so this module cannot import ``cfl_system.lib.exponent_pattern``. Its own
``natural``-kind handling (``_parse_simple_exponent_natural``) is therefore a
small, self-contained subset of that module's grammar (whitespace-separated
``letter^var`` blocks, an optional flat ``| a OP b (and/or ...)*`` condition,
no unions, no arithmetic beyond a bare variable/literal, no multi-letter
units) -- enough for ``agent_system``'s own examples (e.g. ``{a^n b^n | n >=
0}``, reg-01). ``cfl_system.lib.lean_ir`` uses the real, general parser
(``cfl_system.lib.exponent_pattern.parse_exponent_pattern``) for its own
``natural``-kind IRs (unions, richer arithmetic, multi-letter units), feeding
its result into this module's ``pattern_body`` -- so the segments/condition
-> Lean *conversion* logic itself is never duplicated, only the small text
parser is (mirrors the existing precedent of ``dcfl_system.lib.dpda`` keeping
its own field-name convention rather than importing ``cfl_system``'s).

Alphabet type
-------------
``inductive Letter | a | b | c ... deriving DecidableEq, Repr`` -- one named
constructor per letter of ``ir.alphabet`` (or ``language_spec``'s
``terminals``/``alphabet`` field, per IR kind), rather than ``Fin k``.
Reasoning: every generated word literal and grammar rule reads as
``Letter.a``/``Letter.b`` instead of an opaque ``(0 : Fin k)``/``(1 : Fin k)``,
which matters because this text is read by both the LLM formalizer (writing
the proof body against these exact names) and a human auditing a `verified`
result. ``Fin k`` would need the same "letter -> index" bookkeeping duplicated
by every reader; a named inductive puts it in one place (this module) and
erases it from everything downstream. Named ``Letter``, not ``Sym``: Mathlib
already has a top-level ``def Sym (α : Type*) (n : ℕ) := ...`` (symmetric
powers, ``Mathlib.Data.Sym.Basic``, transitively imported by every direction
here) -- ``inductive Sym`` in ``check.lean`` collides with it
("`Sym` has already been declared"), confirmed against the pinned image
(``docker run tfl-lean4``) while writing this module.

``deriving DecidableEq, Repr`` only, **not** ``Fintype``, on the ``Letter``
inductive itself: ``deriving Fintype`` for a plain enum inductive fails to
elaborate under the pinned toolchain, ``leanprover/lean4:v4.33.0``
(confirmed with a minimal ``inductive Letter | a | b deriving Fintype``
against ``docker run tfl-lean4``: `` Tactic `rewrite` failed... Application
type mismatch: ... Letter.enumList_nodup ... expected ...
(↑Letter.enumList).Nodup`` -- a `Finset`/`Multiset` coercion mismatch
inside the derive handler itself, not anything to do with this module's
generated names -- and the hint Lean prints for the error,
``deriving instance Fintype for Letter`` as a separate command, hits the
exact same broken handler). Every ``LeanStatement`` this module or its
``cfl_system``/``dcfl_system`` wrappers ever produced with ``Fintype`` in
the ``deriving`` clause would have failed to type-check regardless of the
proof body.

Whether a ``Fintype Letter`` instance is needed at all depends on the
direction: ``Language.IsRegular``/``Language.IsContextFree``
(``Mathlib.Computability.{DFA, ContextFreeGrammar}``) quantify ``Fintype``
over the automaton's *state* type only, never over the alphabet -- REG/CFL
statements need nothing beyond ``DecidableEq Letter``. langlib's
``is_DCF``/``is_DPDA`` (``Langlib/Automata/DeterministicPushdown/
Definition.lean``: ``is_DPDA {T : Type} [Fintype T] (L : Language T) :
Prop``) is the opposite: it takes ``[Fintype T]`` on the alphabet as an
explicit instance argument, so a DCFL statement genuinely cannot elaborate
without one (confirmed: ``dcfl_system.lib.lean_ir``'s statements fail
``failed to synthesize instance ... Fintype Letter`` against ``docker run
tfl-lean4`` without it). ``fintype_instance_decl(sym_map)`` is the
workaround: a literal ``Finset`` of every constructor plus a ``decide``d
completeness proof (``instance : Fintype Letter where elems := {Letter.a,
...}; complete := by intro x; cases x <;> decide``), which *does* compile
-- ``dcfl_system.lib.lean_ir`` appends it after ``alphabet_decl`` for both
its directions; ``agent_system.lib.lean_ir``/``cfl_system.lib.lean_ir``
never call it, since REG/CFL statements don't need it and it would just be
dead code in their generated files.

CFL/DCFL predicate provenance
------------------------------
Checked directly against the pinned toolchain (``agent_system/docker/tfl_lean``,
``leanprover/lean4:v4.33.0`` + Mathlib, ``lake exe cache get`` already warms
the *whole* Mathlib .olean cache, confirmed via ``docker run tfl-lean4`` while
writing this module) and against a read-only reference clone of ``langlib``
(commit ``c5fb8340b42543713f79e1c283a3f6a929cb71ef``, ``lean-toolchain``
v4.33.0) kept outside the repo for the duration of this work -- it is
reference-only, never imported at runtime and not wired into any test's
lookup path; grep it directly (``Langlib/Classes/...``) when re-checking a
predicate/lemma name below:

- **REG**: Mathlib's own ``Language.IsRegular`` (``Mathlib.Computability.Language``,
  transitively available once ``Mathlib.Computability.RegularExpressions``
  is imported, which ``TflLean`` already does) -- langlib's own regularity
  class (``is_RG``, ``Langlib/Grammars/RightRegular/Definition.lean``) is a
  *different*, grammar-shaped definition its examples don't actually use for
  proofs (``Langlib/Classes/Regular/Examples/AnBn.lean`` proves
  ``anbn_not_isRegular : ¬ anbn.IsRegular`` directly against Mathlib's
  predicate via ``Language.isRegular_iff_finite_range_leftQuotient``).
- **CFL**: Mathlib's own ``Language.IsContextFree`` (``∃ g : ContextFreeGrammar
  T, g.language = L`` -- ``Mathlib.Computability.ContextFreeGrammar``), *not*
  langlib's own ``is_CF`` (``Langlib/Classes/ContextFree/Definition.lean``,
  built over langlib's separate unrestricted-``grammar`` type). The two are
  proved equivalent by langlib itself (``is_CF_iff_isContextFree``), and
  critically langlib proves its pumping lemma and Ogden's lemma **directly
  in Mathlib's own namespace**: ``Language.IsContextFree.pumping``
  (``Langlib/Classes/ContextFree/Pumping/Pumping.lean``) and
  ``Language.IsContextFree.ogdens_lemma``
  (``Langlib/Classes/ContextFree/Basics/Ogden.lean``) -- so
  ``Language.IsContextFree`` is "the one with the pumping lemma" the task
  asked to identify, while also being the Mathlib-native predicate that only
  needs ``import Mathlib.Computability.ContextFreeGrammar`` to *state* (no
  langlib dependency for the statement itself, only for a ``non_cfl`` proof
  body that cites the pumping/Ogden lemmas).
- **DCFL**: Mathlib has no deterministic-pushdown-automaton formalization at
  all (``grep``ped ``Mathlib/Computability/`` while writing this module: no
  hit), so the DCFL direction uses langlib's own ``is_DCF``
  (``Langlib/Classes/DeterministicContextFree/Definition.lean``:
  ``is_DCF (L : Language T) : Prop := is_DPDA L``, over langlib's own DPDA
  automaton type) -- there is no alternative.
- **langlib availability**: ``agent_system/docker/tfl_lean/lakefile.toml``
  now pins ``langlib`` as a Lake dependency (``rev
  c5fb8340b42543713f79e1c283a3f6a929cb71ef``, matching the reference clone
  above) and the pinned ``tfl-lean4`` image has it built in
  (``docker run tfl-lean4 ls .lake/packages/`` lists ``langlib`` alongside
  ``mathlib``, confirmed while writing this module) -- so, as of this
  module, statements for every direction (including ``cfl``/``non_cfl``/
  ``dcfl``/``non_dcfl`` with their real ``Langlib.Classes...`` imports, not
  a stripped-imports substitute) actually type-check against the current
  image; ``cfl_system.lib.lean_ir``'s and ``dcfl_system.lib.lean_ir``'s own
  Docker-conditional tests exercise this directly.

LL(k)
-----
Always ``None`` (``direction == "ll"``): LL(k)-ness is a property of a
*grammar*'s parsing algorithm, not of the language it generates, so "is this
language LL(k)" isn't even a well-formed Mathlib/langlib statement the way
regularity/CFL-ness/DCFL-ness are (see docs/VERDICT_POLICY.md R-Lean: "LL(k)
— не формализуется").

Language construction
----------------------
- ``grammar`` kind -> Mathlib ``ContextFreeGrammar Letter`` (``g``) with
  ``L := g.language`` (used for all three of reg/cfl/dcfl -- e.g. dcfl's
  exam_04, ``task_grammar_aSSb``, is a grammar IR). The rules are a ``Finset``
  of ``ContextFreeRule``, so ε-rules (``rhs == []``) and unit rules
  (``A -> B``) need no special handling; the nonterminals become their own
  ``inductive NT``. A symbol that is both a terminal and a nonterminal is
  ambiguous and yields ``None``. ``cfl_system``'s ``grammar_filter`` adds
  ``⊓ {w | <filter>}`` to the language (``grammar_decl(filter_body=...)``).
- ``regex`` kind (``has_backreferences: false`` only -- ``true`` means the
  pattern isn't a regular expression at all and is rejected with a reason)
  -> Mathlib ``RegularExpression Letter`` (``re``) with ``L := re.matches'``.
  Supports literal alphabet characters, ``|`` (union), implicit
  concatenation, ``*``/``+``/``?`` (postfix repetition/optional) and ``()``
  grouping -- i.e. plain regular-expression syntax, nothing POSIX-specific
  (no character classes, no anchors, no backreferences).
- ``natural`` kind with exponent notation -- ``{a^n b^n c^m | ...}`` style --
  via ``List.replicate``/(for multi-letter units) ``List.replicate ... .flatten``
  segments existentially quantified over ℕ, `w = <segments>`` conjoined with
  the (optional) condition. A word this shape describes needn't be
  "resolvable" the way ``cfl_system.lib.exponent_pattern``'s runtime *oracle*
  needs to be (see that module's docstring) -- a Lean ``Prop`` is just an
  existentially-quantified equation, not an algorithm, so this module
  supports strictly more IR than that module's ``accepts()`` can decide.
  What it does *not* support: ``-`` (unbounded ℕ subtraction would silently
  change the meaning) anywhere in an exponent expression.
- ``natural`` kind describing a palindrome (``w = reverse(w)`` / ``w = w^R`` /
  ``w = wᴿ``, case-insensitively) -> ``L := {w : List Letter | w = w.reverse}``.
  The optional ``w ∈ SET`` in front of the ``|`` must be ``Σ*``/``{a,b}*`` (see
  ``_alphabet_set``): the full alphabet gives the bare palindrome language, a
  proper subset adds ``∧ ∀ ch ∈ w, ch = Letter.a ∨ ...``, anything else is
  ``None`` -- a set-builder domain is never silently dropped.
- ``natural`` kind of the *word templates* ``{w wᴿ | w ∈ Σ*}``,
  ``{w c wᴿ | w ∈ Σ*}`` (``c`` a letter of the alphabet) and the copy twins
  ``{w w | ...}``/``{w c w | ...}`` -> ``∃ u : List Letter, w = u ++ u.reverse``
  / ``w = u ++ [Letter.c] ++ u.reverse`` / ``w = u ++ u`` / ...
  (``word_template_body``; ``fullmatch`` against the whole description, like
  the palindrome, so extra clauses make it ``None``).
- **Composites** (``build_language``): a ``language_spec`` of ``kind``
  ``"union"``/``"intersection"`` with ``branches`` (each a language_spec or a
  natural-description string), and -- for ``natural`` descriptions that no
  single-language translation accepts -- a top-level ``A ∪ B`` /
  ``A union B`` / ``A ∩ B`` / ``A intersect B`` split (brace depth 0), are
  translated branch by branch into ``L_1``, ``L_2``, ... (helper
  definitions carry the same ``_i`` suffix: ``NT_1``/``g_1``/``re_1``) and
  combined as ``L := L_1 ⊔ L_2`` / ``L_1 ⊓ L_2`` -- Mathlib's ``Language`` is
  a ``CompleteAtomicBooleanAlgebra`` whose ``⊔``/``⊓`` are union/intersection.
  An exponent-notation ``A union B`` that the (cfl/dcfl) exponent parser
  handles in one piece keeps its ``∨``-of-``∃`` form (pinned by golden tests).
- Anything else (``predicate``, ``arithmetic_index``, cfl's
  ``repeated_subword``, a ``natural`` description that is neither exponent
  notation nor a simple palindrome/reversal template, a dcfl ``set_builder``
  that isn't the letter-domain shape ``cfl_system/lib/lean_ir.py`` and
  ``dcfl_system/lib/lean_ir.py`` handle) ->
  ``None`` with a reason. This module never invents a formalization for
  something it cannot mechanically translate.

Decidable companion (``LeanStatement.decidable_decl``)
-------------------------------------------------------
``L`` itself is a ``Set (List Letter)`` with (for exponent patterns) an
*unbounded* ``∃ n : ℕ`` -- Lean cannot ``decide`` membership. For
every language this module renders whose membership is computable it also
produces ``def Lb (w : List Letter) : Bool := decide (<Prop>)`` where the
``Prop`` is *equivalent* to the language's body but decidable:

- exponent patterns: every ``∃ n : ℕ`` becomes ``∃ n : ℕ, n < w.length + 1 ∧ ...``
  -- sound exactly when each variable is bounded by the word's length, which
  ``_bounded_by_var`` proves syntactically (a block ``a^e`` with ``e ≥ n`` as
  a naturals fact: ``e = n``, ``n + ...``, ``k * n`` for a numeral ``k ≥ 1``,
  ``n * n``); a variable that appears only in the condition makes the
  companion ``None`` (never a guess);
- word templates: ``u`` is forced to be ``w.take (w.length / 2)``;
- regex: ``RegularExpression.rmatch``; union/intersection of decidable
  branches: ``||``/``&&``;
- grammar languages have no companion (derivability is not decidable by
  ``decide``); a ``grammar_filter`` gets ``Fb``, the *filter part only*
  (``decidable_covers == "filter_only"``).

The companion is never part of the theorem file (``LeanStatement.render``
ignores it): it exists so tests -- and anyone auditing a ``verified`` result
-- can ``#eval`` the generated formulation against the task's Python oracle
on short words and see that the Lean text means what the IR means.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

__all__ = [
    "COMPOSITE_KINDS",
    "LangDef",
    "LeanStatement",
    "alphabet_decl",
    "build_language",
    "combine_languages",
    "composite_alphabet",
    "fintype_instance_decl",
    "grammar_decl",
    "letters_only",
    "make_statement",
    "palindrome_body",
    "parse_regex",
    "pattern_body",
    "pattern_tree_body",
    "predicate_to_lean",
    "render_statement",
    "render_statement_verbose",
    "set_language",
    "word_template_body",
]

# ---------------------------------------------------------------------------
# LeanStatement
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LeanStatement:
    """A deterministically-generated Lean 4 theorem formulation.

    ``alphabet_decl``: the ``inductive Letter ...`` declaration.
    ``language_decl``: whatever else the statement needs (grammar/regex/`NT`
      declarations and ``def L : Language Letter := ...``).
    ``theorem_decl``: ``"theorem tfl_main : <Prop>"`` -- no ``:= by ...``;
      :meth:`render` appends that with the harness-supplied proof body.
    ``imports``: full ``import ...`` lines, in the order they should appear,
      always starting with ``"import TflLean"``.
    ``name``: the theorem's name (``"tfl_main"`` -- R-Lean's fixed contract).
    ``decidable_decl``: optional Lean text defining ``def <decidable_name> (w :
      List Letter) : Bool`` -- a decidable, provably equivalent form of the
      language (module docstring, "Decidable companion"). Never part of
      :meth:`render`; for ``#eval``-ing the statement against an oracle in
      tests. ``None`` when the language has no such form (grammar languages).
    ``decidable_name``: ``"Lb"``; ``decidable_covers``: ``"language"`` (``Lb``
      decides ``L``) or ``"filter_only"`` (``Fb`` decides only the filter
      part of a ``grammar_filter`` language).
    """

    alphabet_decl: str
    language_decl: str
    theorem_decl: str
    imports: list[str] = field(default_factory=list)
    name: str = "tfl_main"
    decidable_decl: str | None = None
    decidable_name: str = "Lb"
    decidable_covers: str = "language"

    def render(self, proof: str = "sorry") -> str:
        """Assemble the full ``.lean`` file text, substituting *proof* into
        the ``:= by`` block. The harness substitutes the formalizer LLM's
        proof body here; the default ``"sorry"`` is what the Docker-conditional
        syntax-only test in ``agent_system/tests/test_lean_ir.py`` compiles."""
        parts = list(self.imports)
        parts.append("")
        parts.append(self.alphabet_decl)
        parts.append("")
        parts.append(self.language_decl)
        parts.append("")
        parts.append(f"{self.theorem_decl} := by\n  {proof}")
        return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Identifiers
# ---------------------------------------------------------------------------

_LEAN_KEYWORDS = {
    "let", "fun", "match", "with", "do", "if", "then", "else", "by", "from",
    "have", "show", "theorem", "def", "inductive", "structure", "class",
    "instance", "import", "open", "namespace", "end", "variable", "variables",
    "where", "deriving", "this", "sorry", "Type", "Prop", "Sort", "forall",
    "exists", "in", "at", "calc", "suffices", "assume", "set_option",
    "section", "mut", "rec", "macro", "syntax", "notation", "attribute",
}
_IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def _safe_ident(raw: str, fallback_prefix: str, idx: int, used: set[str]) -> str:
    """A valid, unused Lean identifier for *raw* (a single IR token -- an
    alphabet letter or a nonterminal name), reusing *raw* verbatim when it
    already is one and isn't a keyword, else falling back to
    ``f"{fallback_prefix}{idx}"``, de-duplicated against *used* (mutated)."""
    cand = raw if (isinstance(raw, str) and _IDENT_RE.fullmatch(raw) and raw not in _LEAN_KEYWORDS) else None
    if cand is None:
        cand = f"{fallback_prefix}{idx}"
    base = cand
    n = 1
    while cand in used:
        cand = f"{base}_{n}"
        n += 1
    used.add(cand)
    return cand


def alphabet_decl(symbols: list) -> tuple[str, dict[str, str]] | None:
    """``inductive Letter | <ctor> | ... deriving DecidableEq, Repr`` (not
    ``Fintype`` -- see the module docstring's "Alphabet type" section) for
    the (order-preserving, de-duplicated) *symbols*, plus the
    ``{original symbol: Lean constructor name}`` map. ``None`` if *symbols*
    isn't a non-empty list of non-empty strings."""
    if not isinstance(symbols, list):
        return None
    seen: list[str] = []
    for s in symbols:
        if not isinstance(s, str) or not s:
            return None
        if s not in seen:
            seen.append(s)
    if not seen:
        return None
    used: set[str] = set()
    mapping: dict[str, str] = {}
    for i, s in enumerate(seen):
        mapping[s] = _safe_ident(s, "t", i, used)
    ctor_list = " | ".join(mapping[s] for s in seen)
    decl = (
        "inductive Letter\n"
        f"  | {ctor_list}\n"
        "  deriving DecidableEq, Repr"
    )
    return decl, mapping


def fintype_instance_decl(sym_map: dict[str, str]) -> str | None:
    """A hand-written ``instance : Fintype Letter where ...`` for the
    ``Letter`` inductive *sym_map* (``alphabet_decl``'s second return value)
    names -- for statements that actually need ``Fintype Letter`` (langlib's
    ``is_DPDA``/``is_DCF`` do, via ``DPDA``'s ``[Fintype T]`` -- confirmed
    against ``docker run tfl-lean4``: ``dcfl_system.lib.lean_ir``'s
    statements fail with ``failed to synthesize instance ... Fintype
    Letter`` without this. ``Language.IsRegular``/``Language.IsContextFree``
    do not, see the module docstring's "Alphabet type" section, so
    ``agent_system.lib.lean_ir``/``cfl_system.lib.lean_ir`` never call this).

    Deliberately **not** ``deriving Fintype`` (broken on the pinned
    toolchain for a plain enum inductive, see "Alphabet type" above) or the
    hint-suggested standalone ``deriving instance Fintype for Letter``
    (same derive handler, same failure) -- a literal ``Finset`` of every
    constructor plus a ``decide``d completeness proof, which *does* compile
    (confirmed against ``docker run tfl-lean4`` while writing this module).
    ``None`` if *sym_map* is empty (mirrors ``alphabet_decl``, which never
    itself returns an empty mapping, but this function stays a pure,
    independently-callable sibling)."""
    if not sym_map:
        return None
    elems = "{" + ", ".join(f"Letter.{ctor}" for ctor in sym_map.values()) + "}"
    return (
        "instance : Fintype Letter where\n"
        f"  elems := {elems}\n"
        "  complete := by intro x; cases x <;> decide"
    )


# ---------------------------------------------------------------------------
# Grammar -> Mathlib ContextFreeGrammar
# ---------------------------------------------------------------------------


def grammar_decl(
    lang_spec: dict,
    sym_map: dict[str, str],
    *,
    suffix: str = "",
    filter_body: str | None = None,
) -> str | None:
    """``inductive NT ...`` + ``def g : ContextFreeGrammar Letter := ...`` +
    ``def L : Language Letter := g.language`` for a ``kind == "grammar"``
    ``language_spec`` (``nonterminals``, ``start``, ``rules: [{lhs, rhs}]``).
    Every ``rhs`` token must be a member of *sym_map* (a terminal) or of
    ``nonterminals`` (never both -- a token that is both is ambiguous);
    ε-rules (``rhs == []``) and unit rules are ordinary rules. ``None`` on any
    other malformed/unsupported shape.

    *suffix* renames ``NT``/``g``/``L`` to ``NT<suffix>``/``g<suffix>``/
    ``L<suffix>`` (composite branches, see :func:`build_language`).
    *filter_body*, a ``Prop`` over the word ``w`` (``grammar_filter``), makes
    ``L := g.language ⊓ {w : List Letter | <filter_body>}``."""
    if not isinstance(lang_spec, dict):
        return None
    nonterminals = lang_spec.get("nonterminals")
    start = lang_spec.get("start")
    rules = lang_spec.get("rules")
    if not (isinstance(nonterminals, list) and isinstance(start, str) and isinstance(rules, list)):
        return None
    if not nonterminals or start not in nonterminals:
        return None

    seen_nt: list[str] = []
    for n in nonterminals:
        if not isinstance(n, str) or not n:
            return None
        if n not in seen_nt:
            seen_nt.append(n)
    if any(n in sym_map for n in seen_nt):
        return None  # a symbol that is both a terminal and a nonterminal is ambiguous

    used: set[str] = set()
    nt_map: dict[str, str] = {}
    for i, n in enumerate(seen_nt):
        nt_map[n] = _safe_ident(n, "N", i, used)

    nt_type = f"NT{suffix}"
    rule_texts: list[str] = []
    for rule in rules:
        if not isinstance(rule, dict):
            return None
        lhs = rule.get("lhs")
        rhs = rule.get("rhs")
        if lhs not in nt_map or not isinstance(rhs, list):
            return None
        sym_texts: list[str] = []
        for tok in rhs:
            if tok in nt_map:
                sym_texts.append(f"Symbol.nonterminal {nt_type}.{nt_map[tok]}")
            elif tok in sym_map:
                sym_texts.append(f"Symbol.terminal Letter.{sym_map[tok]}")
            else:
                return None
        rule_texts.append(f"⟨{nt_type}.{nt_map[lhs]}, [{', '.join(sym_texts)}]⟩")

    nt_ctor_list = " | ".join(nt_map[n] for n in seen_nt)
    nt_decl = f"inductive {nt_type}\n  | {nt_ctor_list}\n  deriving DecidableEq, Repr"
    rules_set = "{" + ", ".join(rule_texts) + "}"

    if filter_body is None:
        lang_line = f"def L{suffix} : Language Letter := g{suffix}.language"
    else:
        lang_line = (
            f"def L{suffix} : Language Letter := g{suffix}.language ⊓ "
            f"({{w : List Letter | {filter_body}}} : Language Letter)"
        )
    return (
        f"{nt_decl}\n\n"
        f"def g{suffix} : ContextFreeGrammar Letter :=\n"
        f"  {{ NT := {nt_type}, initial := {nt_type}.{nt_map[start]}, rules := {rules_set} }}\n\n"
        f"{lang_line}"
    )


# ---------------------------------------------------------------------------
# Regex -> Mathlib RegularExpression (no backreferences)
# ---------------------------------------------------------------------------


def parse_regex(pattern: str, sym_map: dict[str, str]) -> str | None:
    """A ``RegularExpression Letter`` term for *pattern* (alphabet chars, ``|``,
    implicit concatenation, postfix ``*``/``+``/``?``, ``()`` grouping) --
    ``None`` for anything else (backreferences, character classes, anchors,
    unrecognized characters, or a character outside *sym_map*)."""
    if not isinstance(pattern, str):
        return None
    pos = [0]
    n = len(pattern)

    def peek() -> str | None:
        return pattern[pos[0]] if pos[0] < n else None

    def advance() -> str:
        c = pattern[pos[0]]
        pos[0] += 1
        return c

    def parse_union() -> str | None:
        left = parse_concat()
        if left is None:
            return None
        while peek() == "|":
            advance()
            right = parse_concat()
            if right is None:
                return None
            left = f"({left} + {right})"
        return left

    def parse_concat() -> str | None:
        parts: list[str] = []
        while True:
            c = peek()
            if c is None or c in "|)":
                break
            atom = parse_star()
            if atom is None:
                return None
            parts.append(atom)
        if not parts:
            return "RegularExpression.epsilon"
        expr = parts[0]
        for p in parts[1:]:
            expr = f"({expr} * {p})"
        return expr

    def parse_star() -> str | None:
        atom = parse_atom()
        if atom is None:
            return None
        while peek() in ("*", "+", "?"):
            op = advance()
            if op == "*":
                atom = f"(RegularExpression.star {atom})"
            elif op == "+":
                atom = f"({atom} * RegularExpression.star {atom})"
            else:  # "?"
                atom = f"(RegularExpression.epsilon + {atom})"
        return atom

    def parse_atom() -> str | None:
        c = peek()
        if c is None:
            return None
        if c == "(":
            advance()
            inner = parse_union()
            if inner is None or peek() != ")":
                return None
            advance()
            return inner
        if c in sym_map:
            advance()
            return f"(RegularExpression.char Letter.{sym_map[c]})"
        return None

    result = parse_union()
    if result is None or pos[0] != n:
        return None
    return result


# ---------------------------------------------------------------------------
# Exponent-notation segments/condition -> Lean (shared converter; the parser
# that PRODUCES segments/condition is elsewhere -- see module docstring).
#
# ``segments``: list of ``{"literal": str}`` or ``{"unit": str, "expr": Expr}``.
# ``condition``: ``None`` or a boolean-condition AST node.
# ``Expr``    := ("num", int) | ("var", str) | ("bin", "+"|"*", Expr, Expr)
#                -- NOT "-"/"neg": unbounded truncating subtraction in ℕ
#                would silently change the statement's meaning, so any
#                expression using it is rejected (``None``).
# ``Cond``    := ("chain", [[Expr]], [op]) | ("not", Cond) | ("and"|"or", [Cond])
#                -- exactly cfl_system.lib.exponent_pattern's shapes (its
#                ``ExponentPattern.segments``/``.condition`` fields), so
#                ``cfl_system.lib.lean_ir`` can feed this function that
#                module's *real* parser output directly.
# ---------------------------------------------------------------------------

_REL_LEAN = {"==": "=", "!=": "≠", "<": "<", "<=": "≤", ">": ">", ">=": "≥"}


def _expr_vars(expr: tuple) -> set[str]:
    kind = expr[0]
    if kind == "var":
        return {expr[1]}
    if kind == "bin":
        return _expr_vars(expr[2]) | _expr_vars(expr[3])
    return set()


def _cond_vars(node: tuple) -> set[str]:
    kind = node[0]
    if kind == "chain":
        vs: set[str] = set()
        for group in node[1]:
            for e in group:
                vs |= _expr_vars(e)
        return vs
    if kind == "not":
        return _cond_vars(node[1])
    if kind in ("and", "or"):
        vs = set()
        for n in node[1]:
            vs |= _cond_vars(n)
        return vs
    return set()


def _expr_to_lean(expr: tuple, var_names: dict[str, str]) -> str | None:
    kind = expr[0]
    if kind == "num":
        return str(expr[1])
    if kind == "var":
        return var_names.get(expr[1])
    if kind == "bin":
        _, op, l, r = expr
        if op not in ("+", "*"):
            return None
        ls = _expr_to_lean(l, var_names)
        rs = _expr_to_lean(r, var_names)
        if ls is None or rs is None:
            return None
        return f"({ls} + {rs})" if op == "+" else f"({ls} * {rs})"
    return None


def _cond_to_lean(node: tuple, var_names: dict[str, str]) -> str | None:
    kind = node[0]
    if kind == "chain":
        _, groups, ops = node
        parts: list[str] = []
        for i, op in enumerate(ops):
            lean_op = _REL_LEAN.get(op)
            if lean_op is None:
                return None
            for le in groups[i]:
                for re_ in groups[i + 1]:
                    ls = _expr_to_lean(le, var_names)
                    rs = _expr_to_lean(re_, var_names)
                    if ls is None or rs is None:
                        return None
                    parts.append(f"{ls} {lean_op} {rs}")
        return " ∧ ".join(parts) if parts else None
    if kind == "not":
        inner = _cond_to_lean(node[1], var_names)
        return None if inner is None else f"¬ ({inner})"
    if kind in ("and", "or"):
        parts = [_cond_to_lean(n, var_names) for n in node[1]]
        if any(p is None for p in parts):
            return None
        sep = " ∧ " if kind == "and" else " ∨ "
        return "(" + sep.join(parts) + ")"
    return None


def _segments_to_lean(segments: list[dict], sym_map: dict[str, str], var_names: dict[str, str]) -> str | None:
    parts: list[str] = []
    for seg in segments:
        if "literal" in seg:
            lit = seg["literal"]
            if not lit:
                continue
            if any(ch not in sym_map for ch in lit):
                return None
            parts.append("[" + ", ".join(f"Letter.{sym_map[ch]}" for ch in lit) + "]")
            continue
        unit = seg.get("unit")
        expr = seg.get("expr")
        if not unit or expr is None:
            return None
        count_lean = _expr_to_lean(expr, var_names)
        if count_lean is None:
            return None
        if len(unit) == 1:
            if unit not in sym_map:
                return None
            parts.append(f"List.replicate {count_lean} Letter.{sym_map[unit]}")
        else:
            if any(ch not in sym_map for ch in unit):
                return None
            lit_list = "[" + ", ".join(f"Letter.{sym_map[ch]}" for ch in unit) + "]"
            parts.append(f"(List.replicate {count_lean} {lit_list}).flatten")
    return " ++ ".join(parts) if parts else "[]"


def _bounded_by_var(expr: tuple, v: str) -> bool:
    """``True`` if the exponent expression *expr* is provably ``≥ v`` for
    every assignment of naturals (the syntactic sufficient conditions the
    module docstring lists), so ``v ≤`` the block's length ``≤ |w|``."""
    kind = expr[0]
    if kind == "var":
        return expr[1] == v
    if kind == "bin":
        _, op, l, r = expr
        if op == "+":
            return _bounded_by_var(l, v) or _bounded_by_var(r, v)
        if op == "*":
            if l == r:  # e * e ≥ e for every natural e
                return _bounded_by_var(l, v)
            if l[0] == "num" and l[1] >= 1:
                return _bounded_by_var(r, v)
            if r[0] == "num" and r[1] >= 1:
                return _bounded_by_var(l, v)
    return False


def pattern_body(
    segments: list[dict],
    condition: tuple | None,
    sym_map: dict[str, str],
    *,
    decidable: bool = False,
) -> str | None:
    """The set-builder body (without the surrounding ``{w : List Letter | ...}``)
    for one exponent-notation branch: ``∃ <vars> : ℕ, w = <segments> [∧
    <condition>]``, or just ``w = <segments>`` when no variable appears
    anywhere. ``None`` if *segments*/*condition* use anything this converter
    doesn't support (a letter outside *sym_map*, ``-`` in an exponent, an
    unrecognized condition shape).

    ``decidable=True`` renders the equivalent *decidable* ``Prop`` for
    ``LeanStatement.decidable_decl``: each ``∃ n : ℕ`` gets the bound
    ``n < w.length + 1``, which is sound only if every variable is provably
    ``≤ |w|`` (``_bounded_by_var`` on some block's exponent); otherwise
    ``None``."""
    if not isinstance(segments, list) or not segments:
        return None
    block_vars: set[str] = set()
    for seg in segments:
        if "expr" in seg:
            block_vars |= _expr_vars(seg["expr"])
    cond_vars = _cond_vars(condition) if condition is not None else set()
    all_vars = sorted(block_vars | cond_vars)

    used = {"w"}
    var_names: dict[str, str] = {}
    for v in all_vars:
        ident = v
        while ident in used:
            ident = f"{ident}_"
        var_names[v] = ident
        used.add(ident)

    word_expr = _segments_to_lean(segments, sym_map, var_names)
    if word_expr is None:
        return None

    clauses = [f"w = {word_expr}"]
    if condition is not None:
        cond_text = _cond_to_lean(condition, var_names)
        if cond_text is None:
            return None
        clauses.append(cond_text)
    body = " ∧ ".join(clauses)
    if not all_vars:
        return body
    if decidable:
        for v in all_vars:
            if not any(
                "expr" in seg and seg.get("unit") and _bounded_by_var(seg["expr"], v)
                for seg in segments
            ):
                return None
        inner = body
        for v in reversed(all_vars):
            n = var_names[v]
            inner = f"∃ {n} : ℕ, {n} < w.length + 1 ∧ {inner}"
        return inner
    quant = " ".join(var_names[v] for v in all_vars)
    return f"∃ {quant} : ℕ, {body}"


def pattern_tree_body(pattern, sym_map: dict[str, str], *, decidable: bool = False) -> str | None:
    """:func:`pattern_body` for a parsed exponent pattern, or the ``∨``-join of
    it over each branch of a union (duck-typed: ``.segments``/``.condition``
    for one pattern, ``.parts`` for a union -- ``cfl_system.lib
    .exponent_pattern``'s ``ExponentPattern``/``_UnionPattern``, which this
    module may not import)."""
    segments = getattr(pattern, "segments", None)
    if segments is not None:
        return pattern_body(segments, getattr(pattern, "condition", None), sym_map, decidable=decidable)
    parts = getattr(pattern, "parts", None)
    if not parts:
        return None
    bodies = [pattern_tree_body(p, sym_map, decidable=decidable) for p in parts]
    if any(b is None for b in bodies):
        return None
    return " ∨ ".join(f"({b})" for b in bodies)


# ---------------------------------------------------------------------------
# agent_system's own minimal exponent-notation parser (natural kind, REG
# direction only) -- see module docstring for why this is a small local
# subset rather than an import of cfl_system.lib.exponent_pattern.
# ---------------------------------------------------------------------------

_BLOCK_TOKEN_RE = re.compile(r"([A-Za-z])\^\{?([A-Za-z])\}?")
_REL_TOKEN_RE = re.compile(r"(==|!=|<=|>=|<|>|=)")
_AND_OR_SPLIT_RE = re.compile(r"\s+(and|or)\s+", re.IGNORECASE)


def _parse_simple_atom(text: str) -> tuple | None:
    text = text.strip()
    if re.fullmatch(r"[0-9]+", text):
        return ("num", int(text))
    if re.fullmatch(r"[A-Za-z]", text):
        return ("var", text)
    return None


def _parse_simple_condition(text: str) -> tuple | None:
    """``v1 OP v2 (and/or v3 OP v4)*`` -- a flat conjunction/disjunction of
    two-sided comparisons between a single variable and/or integer literal;
    no parentheses, no comma chains, no ``not``, no mixed and/or."""
    parts = _AND_OR_SPLIT_RE.split(text)
    clauses = parts[0::2]
    joiners = [p.lower() for p in parts[1::2]]
    if joiners and any(j != joiners[0] for j in joiners):
        return None
    nodes = []
    for clause in clauses:
        m = _REL_TOKEN_RE.search(clause)
        if not m:
            return None
        op = "==" if m.group(1) == "=" else m.group(1)
        left = _parse_simple_atom(clause[: m.start()])
        right = _parse_simple_atom(clause[m.end():])
        if left is None or right is None:
            return None
        nodes.append(("chain", [[left], [right]], [op]))
    if len(nodes) == 1:
        return nodes[0]
    kind = "and" if not joiners or joiners[0] == "and" else "or"
    return (kind, nodes)


def _parse_simple_exponent_natural(text: str) -> tuple[list[dict], tuple | None] | None:
    if not isinstance(text, str):
        return None
    s = text.strip()
    if s.startswith("{") and s.endswith("}"):
        s = s[1:-1].strip()
    pattern_part, sep, cond_part = s.partition("|")
    pattern_part = pattern_part.strip()
    cond_part = cond_part.strip()

    tokens = pattern_part.split()
    if not tokens:
        return None
    segments = []
    for tok in tokens:
        m = _BLOCK_TOKEN_RE.fullmatch(tok)
        if not m:
            return None
        segments.append({"unit": m.group(1), "expr": ("var", m.group(2))})

    condition = None
    if sep:
        if not cond_part:
            return None
        condition = _parse_simple_condition(cond_part)
        if condition is None:
            return None
    return segments, condition


def _single_char_alphabet(sym_map: dict[str, str]) -> bool:
    """Words are Python strings in every oracle, so a translation that talks
    about "the letters of w" is only faithful when each alphabet symbol is one
    character."""
    return bool(sym_map) and all(isinstance(k, str) and len(k) == 1 for k in sym_map)


_SET_RE = re.compile(r"(?:(?P<sigma>Σ|Sigma)|\{(?P<letters>[^{}]*)\})\s*(?:\^\s*)?\*", re.IGNORECASE)


def _alphabet_set(text: str, sym_map: dict[str, str]) -> tuple[list[str], bool] | None:
    """``(letters, restricted)`` for a domain ``Σ*`` / ``{a, b}*`` /
    ``{a,b}^*`` (``letters``: the letters it allows, in alphabet order;
    ``restricted``: whether that is a proper subset of the alphabet), or
    ``None`` for any other domain text or a letter outside the alphabet."""
    if not isinstance(text, str) or not _single_char_alphabet(sym_map):
        return None
    m = _SET_RE.fullmatch(text.strip())
    if not m:
        return None
    if m.group("sigma"):
        return list(sym_map), False
    raw = [p.strip() for p in m.group("letters").split(",")]
    if not raw or any(len(p) != 1 or p not in sym_map for p in raw):
        return None
    chosen = [letter for letter in sym_map if letter in raw]
    return chosen, len(chosen) != len(sym_map)


def _letters_only(var: str, letters: list[str], sym_map: dict[str, str]) -> str:
    """``∀ ch ∈ var, ch = Letter.a ∨ ch = Letter.b`` for *letters* (the bound
    variable is ``ch``, not ``c``: a letter ``c`` of the alphabet would make
    Lean's ``constructorNameAsVariable`` linter warn)."""
    alts = " ∨ ".join(f"ch = Letter.{sym_map[letter]}" for letter in letters)
    return f"∀ ch ∈ {var}, {alts}"


def _letters_only_all(expr: str, letters: list[str], sym_map: dict[str, str]) -> str:
    """The same statement as a ``List.all`` test -- for the *decidable*
    companion of the reversal templates, where the list is ``w.take (w.length
    / 2)``: the instance search for ``∀ x ∈ w.take (w.length / 2), ...``
    fails on the pinned toolchain (any non-atomic length argument such as
    ``w.length + 1`` does), ``List.all`` elaborates fine."""
    alts = " ∨ ".join(f"ch = Letter.{sym_map[letter]}" for letter in letters)
    return f"({expr}).all (fun ch => decide ({alts})) = true"


def letters_only(var: str, letters: list[str], sym_map: dict[str, str]) -> str:
    """``∀ ch ∈ var, ch = Letter.a ∨ ch = Letter.b`` for *letters* (a non-empty
    list of keys of *sym_map*): "every letter of *var* is one of these"."""
    return _letters_only(var, letters, sym_map)


_PALINDROME_RE = re.compile(
    r"""^\s*
        \{?\s*
        (?:(?P<v0>[A-Za-z])\s*(?:(?:(?i:in)|∈)\s*(?P<set>[^|]*?\*)\s*)?\|\s*)?
        (?P<var>[A-Za-z])\s*
        (?:
            =\s*(?i:reverse)\s*\(\s*(?P=var)\s*\)
            |
            =\s*(?P=var)\s*(?:\^\{?[Rr]\}?|ᴿ)
            |
            (?:\^\{?[Rr]\}?|ᴿ)\s*=\s*(?P=var)
        )
        \s*\}?\s*$
    """,
    re.VERBOSE,  # case-sensitive: the backreference must be the *same* variable
)


def _palindrome_body(description: str, sym_map: dict[str, str] | None = None) -> str | None:
    """Recognize *only* a strict "all palindromes" set-builder description
    -- ``{w (in Sigma*)? | w = reverse(w)}`` (or ``w = w^R`` / ``w^R = w``),
    with nothing else in the body -- via ``fullmatch`` against the whole
    (stripped) description.

    A ``search`` here (the previous implementation) would also match e.g.
    ``{w in {a,b}* | w = reverse(w) and |w| is even}`` or
    ``{w | w = w^R, |w|_a = 2}``: additional conditions the description
    imposes beyond "is a palindrome", silently formalizing the wrong
    (larger) language as "the language of all palindromes". Any extra
    clause must instead make this return ``None`` -- the whole point of
    ``fullmatch``.

    A stated domain (``w in SET*``) is honoured, not ignored: the full
    alphabet is the bare palindrome language, a proper subset of it adds
    ``∧ ∀ ch ∈ w, ...``, and a domain that is not ``Σ*``/``{a,b}*`` (or one
    given while *sym_map* is not) yields ``None``.
    """
    if not isinstance(description, str):
        return None
    m = _PALINDROME_RE.fullmatch(description.strip())
    if not m:
        return None
    if m.group("v0") is not None and m.group("v0") != m.group("var"):
        return None
    dom = m.group("set")
    if dom is None:
        return "w = w.reverse"
    parsed = _alphabet_set(dom, sym_map) if sym_map else None
    if parsed is None:
        return None
    letters, restricted = parsed
    if not restricted:
        return "w = w.reverse"
    return f"w = w.reverse ∧ {_letters_only('w', letters, sym_map)}"


palindrome_body = _palindrome_body


_WORD_TEMPLATE_RE = re.compile(
    r"""(?P<v>[A-Za-z])\s*[·⋅]?\s*
        (?:(?P<c>[^\s·⋅])\s*[·⋅]?\s*)?
        (?:
            (?P=v)\s*(?P<rmark>\^\s*\{?\s*[Rr]\s*\}?|ᴿ)?
            |
            (?P<rfun>(?i:rev|reverse)\s*\(\s*(?P=v)\s*\))
        )""",
    re.VERBOSE,  # case-sensitive: the second occurrence must be the *same* variable
)


def word_template_body(description: str, sym_map: dict[str, str]) -> tuple[str, str] | None:
    """``(prop_body, decidable_body)`` -- both ``Prop`` texts over the word
    ``w`` -- for the strict templates ``{w wᴿ | w ∈ Σ*}``, ``{w c wᴿ | w ∈
    Σ*}`` (``c`` one letter of the alphabet; ``wᴿ`` also ``w^R``/``w^{R}``/
    ``rev(w)``/``reverse(w)``) and their *copy* twins ``{w w | w ∈ Σ*}``,
    ``{w c w | w ∈ Σ*}``; ``| w ∈ Σ*`` is optional, ``Σ*`` also ``{a,b}*``
    (a proper subset of the alphabet restricts ``w`` to it). ``None``
    otherwise.

    ``fullmatch`` against the whole description, so every extra clause (a
    length condition, a second variable, ``w = wᴿ``, ...) rejects it. The
    variable name must not be a letter of the alphabet (``w`` vs ``Letter.w``
    would be ambiguous); ``c`` must be one.

    The decidable form is exact because ``x = u ++ [c] ++ u'`` (``u'`` = ``u``
    or ``u.reverse``) forces ``u = x.take (x.length / 2)``."""
    if not isinstance(description, str) or not _single_char_alphabet(sym_map):
        return None
    text = description.strip()
    text = re.sub(r"^[A-Za-z]\w*\s*=\s*(?=\{)", "", text)  # "L = {...}"
    if text.startswith("{"):
        if not text.endswith("}"):
            return None
        text = text[1:-1].strip()
    elif text.endswith("}"):
        return None
    body_text, sep, cond_text = text.partition("|")
    m = _WORD_TEMPLATE_RE.fullmatch(body_text.strip())
    if not m:
        return None
    v, c = m.group("v"), m.group("c")
    reversed_ = bool(m.group("rmark") or m.group("rfun"))
    if v in sym_map or (c is not None and c not in sym_map):
        return None
    letters, restricted = list(sym_map), False
    if sep:
        cm = re.fullmatch(rf"{re.escape(v)}\s*(?:∈|(?i:in))\s*(?P<set>.+)", cond_text.strip())
        if not cm:
            return None
        parsed = _alphabet_set(cm.group("set"), sym_map)
        if parsed is None:
            return None
        letters, restricted = parsed
    mid = f" ++ [Letter.{sym_map[c]}]" if c is not None else ""
    half = "w.take (w.length / 2)"
    prop = f"∃ u : List Letter, w = u{mid} ++ " + ("u.reverse" if reversed_ else "u")
    dec = f"w = {half}{mid} ++ " + (f"({half}).reverse" if reversed_ else half)
    if restricted:
        prop += f" ∧ {_letters_only('u', letters, sym_map)}"
        dec += f" ∧ {_letters_only_all(half, letters, sym_map)}"
    return prop, dec


# ---------------------------------------------------------------------------
# Predicate IR (agent_system.lib.ir_schema's Expr/Predicate) -> Lean Prop.
#
# Used for ``grammar_filter`` filters and ``exists_decomposition`` constraints
# (cfl_system); *env* maps an IR variable name to the Lean identifier of a
# ``List Letter`` in scope. Mirrors the oracles' semantics exactly
# (agent_system.lib.oracle / cfl_system.lib.cfl_oracle): naturals only, so a
# negative constant is rejected; ``count_subword`` counts overlapping
# occurrences (an empty subword counts 0); ``is_substring``/``starts_with``
# take a literal string over the alphabet unless the operand names a variable
# of *env*. Anything else -> ``None``.
# ---------------------------------------------------------------------------

_CMP_IR_LEAN = {"eq": "=", "neq": "≠", "lt": "<", "leq": "≤", "gt": ">", "geq": "≥"}


def _word_literal(text: str, sym_map: dict[str, str]) -> str | None:
    if not isinstance(text, str) or not _single_char_alphabet(sym_map):
        return None
    if any(ch not in sym_map for ch in text):
        return None
    return "[" + ", ".join(f"Letter.{sym_map[ch]}" for ch in text) + "]"


def _word_operand(name: Any, sym_map: dict[str, str], env: dict[str, str]) -> str | None:
    """A variable of *env* (oracle: ``env.get(name, name)``) or a literal."""
    if not isinstance(name, str):
        return None
    if name in env:
        return env[name]
    return _word_literal(name, sym_map)


def _ir_expr_to_lean(expr: Any, sym_map: dict[str, str], env: dict[str, str]) -> str | None:
    if not isinstance(expr, dict):
        return None
    kind = expr.get("kind")
    if kind == "constant":
        val = expr.get("value")
        if isinstance(val, int) and not isinstance(val, bool) and val >= 0:
            return str(val)
        return None
    if kind == "length":
        of_var = expr.get("of_var")
        x = env.get(of_var) if isinstance(of_var, str) else None
        return None if x is None else f"{x}.length"
    if kind == "count_symbol":
        in_var, sym = expr.get("in_var"), expr.get("symbol")
        x = env.get(in_var) if isinstance(in_var, str) else None
        if x is None or not isinstance(sym, str) or len(sym) != 1 or sym not in sym_map:
            return None
        if not _single_char_alphabet(sym_map):
            return None
        return f"{x}.count Letter.{sym_map[sym]}"
    if kind == "count_subword":
        in_var, sub = expr.get("in_var"), expr.get("subword")
        x = env.get(in_var) if isinstance(in_var, str) else None
        if x is None or not isinstance(sub, str):
            return None
        if sub == "":
            return "0"
        lit = _word_literal(sub, sym_map)
        if lit is None:
            return None
        return f"((List.range {x}.length).countP (fun i => decide ({lit} <+: {x}.drop i)))"
    return None


def predicate_to_lean(pred: Any, sym_map: dict[str, str], env: dict[str, str]) -> str | None:
    """A decidable Lean ``Prop`` for the IR predicate *pred* (``and``/``or``/
    ``not``, the six comparisons, modular, ``is_palindrome``,
    ``is_substring``, ``starts_with`` and their negations), *env* mapping IR
    variable names to Lean ``List Letter`` identifiers; ``None`` for anything
    else (unknown structure, unknown variable, a letter outside the
    alphabet)."""
    if not isinstance(pred, dict):
        return None
    op = pred.get("op")
    if op in ("and", "or", "not"):
        operands = pred.get("operands")
        if not isinstance(operands, list) or not operands:
            return None
        parts = [predicate_to_lean(o, sym_map, env) for o in operands]
        if any(p is None for p in parts):
            return None
        if op == "not":
            return f"¬ ({parts[0]})" if len(parts) == 1 else None
        sep = " ∧ " if op == "and" else " ∨ "
        return sep.join(f"({p})" for p in parts)
    if op in _CMP_IR_LEAN:
        left = _ir_expr_to_lean(pred.get("left"), sym_map, env)
        right = _ir_expr_to_lean(pred.get("right"), sym_map, env)
        if left is None or right is None:
            return None
        return f"{left} {_CMP_IR_LEAN[op]} {right}"
    if op is None and "modulus" in pred and "remainder" in pred and "expr" in pred:
        mod, rem = pred["modulus"], pred["remainder"]
        if not all(isinstance(n, int) and not isinstance(n, bool) for n in (mod, rem)):
            return None
        if mod <= 0 or rem < 0:
            return None
        e = _ir_expr_to_lean(pred["expr"], sym_map, env)
        return None if e is None else f"({e}) % {mod} = {rem}"
    if op in ("is_palindrome", "is_not_palindrome"):
        var = pred.get("var")
        x = env.get(var) if isinstance(var, str) else None
        if x is None:
            return None
        return f"{x} = {x}.reverse" if op == "is_palindrome" else f"¬ ({x} = {x}.reverse)"
    if op in ("is_substring", "is_not_substring"):
        x = env.get(pred.get("in_var")) if isinstance(pred.get("in_var"), str) else None
        sub = _word_operand(pred.get("substring_expr"), sym_map, env)
        if x is None or sub is None:
            return None
        return f"{sub} <:+: {x}" if op == "is_substring" else f"¬ ({sub} <:+: {x})"
    if op in ("starts_with", "not_starts_with"):
        x = env.get(pred.get("of_var")) if isinstance(pred.get("of_var"), str) else None
        pre = _word_operand(pred.get("prefix_expr"), sym_map, env)
        if x is None or pre is None:
            return None
        return f"{pre} <+: {x}" if op == "starts_with" else f"¬ ({pre} <+: {x})"
    return None


# ---------------------------------------------------------------------------
# Language definitions and composites (union / intersection of branches)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LangDef:
    """One translated language. ``decls`` is the Lean text that defines
    ``L<suffix>`` (with any helper definitions it needs, all carrying the same
    suffix); ``decidable`` the optional ``def <decidable_name><suffix> (w :
    List Letter) : Bool`` companion (see ``LeanStatement.decidable_decl``);
    ``covers`` is ``"language"`` or ``"filter_only"``."""

    decls: str
    decidable: str | None = None
    decidable_name: str = "Lb"
    covers: str = "language"


def set_language(
    suffix: str,
    body: str,
    decidable_body: str | None = None,
    *,
    binder: str = "w",
    decidable_prefix: str = "",
) -> LangDef:
    """``def L<suffix> : Language Letter := {<binder> : List Letter | <body>}``
    and, if *decidable_body* is given, ``def Lb<suffix> (<binder> : List
    Letter) : Bool := decide (<decidable_body>)`` (preceded by
    *decidable_prefix*, helper definitions the body uses)."""
    decidable = None
    if decidable_body is not None:
        decidable = (
            f"{decidable_prefix}def Lb{suffix} ({binder} : List Letter) : Bool := "
            f"decide ({decidable_body})"
        )
    return LangDef(f"def L{suffix} : Language Letter := {{{binder} : List Letter | {body}}}", decidable)


def make_statement(alpha_decl: str, ld: LangDef, theorem_decl: str, imports: list[str]) -> LeanStatement:
    """A :class:`LeanStatement` for the translated language *ld*."""
    return LeanStatement(
        alpha_decl,
        ld.decls,
        theorem_decl,
        imports,
        decidable_decl=ld.decidable,
        decidable_name=ld.decidable_name,
        decidable_covers=ld.covers,
    )


_COMPOSITE_OPS = {"union": ("⊔", "||"), "intersection": ("⊓", "&&")}
COMPOSITE_KINDS = frozenset(_COMPOSITE_OPS)
_UNION_TOKEN_RE = re.compile(r"\bunion\b|∪", re.IGNORECASE)
_INTERSECTION_TOKEN_RE = re.compile(r"\bintersect(?:ion)?\b|∩", re.IGNORECASE)


def combine_languages(kind: str, subs: list[LangDef], suffix: str) -> LangDef | None:
    """``L<suffix> := L<suffix>_1 ⊔ L<suffix>_2 ...`` (``"union"``) or ``⊓``
    (``"intersection"``) over *subs* (already rendered with suffixes
    ``<suffix>_1``, ``<suffix>_2``, ...); the decidable companion is the
    ``||``/``&&`` of the branches' when every branch has one covering its
    whole language."""
    if kind not in _COMPOSITE_OPS or len(subs) < 2:
        return None
    op_lang, op_bool = _COMPOSITE_OPS[kind]
    names = [f"L{suffix}_{i}" for i in range(1, len(subs) + 1)]
    decls = "\n\n".join(sd.decls for sd in subs) + f"\n\ndef L{suffix} : Language Letter := " + f" {op_lang} ".join(names)
    decidable = None
    if all(sd.decidable and sd.covers == "language" and sd.decidable_name == "Lb" for sd in subs):
        expr = f" {op_bool} ".join(f"Lb{suffix}_{i} w" for i in range(1, len(subs) + 1))
        decidable = "\n\n".join(sd.decidable for sd in subs) + f"\n\ndef Lb{suffix} (w : List Letter) : Bool := {expr}"
    return LangDef(decls, decidable)


def _split_top_level(text: str, token_re: re.Pattern) -> list[str]:
    """Split *text* at the matches of *token_re* that sit at brace/paren/
    bracket depth 0; ``[text]`` if there is none or a piece would be empty."""
    depth_at: list[int] = []
    depth = 0
    for ch in text:
        if ch in "{([":
            depth += 1
        elif ch in "})]":
            depth = max(0, depth - 1)
        depth_at.append(depth)
    pieces: list[str] = []
    last = 0
    for m in token_re.finditer(text):
        if depth_at[m.start()] == 0:
            pieces.append(text[last:m.start()].strip())
            last = m.end()
    if not pieces:
        return [text]
    pieces.append(text[last:].strip())
    if any(not p for p in pieces):
        return [text]
    return pieces


def build_language(spec: Any, sym_map: dict[str, str], suffix: str, leaf) -> LangDef | None:
    """Translate *spec* (a language_spec dict, or a bare natural-description
    string) into a :class:`LangDef` whose top definition is ``L<suffix>``.

    * ``kind`` ``"union"``/``"intersection"`` with ``branches`` (>= 2): each
      branch is translated recursively under ``<suffix>_<i>`` and combined by
      :func:`combine_languages` -- ``⊔``/``⊓`` of Mathlib's ``Language``
      lattice.
    * any other kind: ``leaf(spec, sym_map, suffix)`` (the direction's own
      single-language translator, ``None`` if it cannot);
    * a ``natural`` spec its leaf cannot translate whose description is a
      top-level ``A ∪ B``/``A union B`` (resp. ``A ∩ B``/``A intersect B``)
      is split and treated as the composite of its parts (union binds looser
      than intersection).

    ``None`` if any part fails -- never a partial or guessed result."""
    if isinstance(spec, str):
        spec = {"kind": "natural", "description": spec}
    if not isinstance(spec, dict):
        return None
    kind = spec.get("kind")
    if kind in _COMPOSITE_OPS:
        branches = spec.get("branches")
        if not isinstance(branches, list) or len(branches) < 2:
            return None
        subs = [build_language(b, sym_map, f"{suffix}_{i}", leaf) for i, b in enumerate(branches, start=1)]
        if any(sd is None for sd in subs):
            return None
        return combine_languages(kind, subs, suffix)
    single = leaf(spec, sym_map, suffix)
    if single is not None or kind != "natural":
        return single
    description = spec.get("description")
    if not isinstance(description, str):
        return None
    for comp_kind, token_re in (("union", _UNION_TOKEN_RE), ("intersection", _INTERSECTION_TOKEN_RE)):
        pieces = _split_top_level(description, token_re)
        if len(pieces) >= 2:
            branches = [{**spec, "description": p} for p in pieces]
            return build_language({"kind": comp_kind, "branches": branches}, sym_map, suffix, leaf)
    return None


def composite_alphabet(ir: dict, spec: dict) -> list[str] | None:
    """The alphabet symbols for a composite *spec*: the IR's (or the spec's)
    declared ``alphabet``, else the ordered union of what its branches
    declare (grammar terminals, ``alphabet`` fields, ``exists_decomposition``
    part alphabets); ``None`` if nothing is declared anywhere."""
    declared = ir.get("alphabet") if isinstance(ir, dict) else None
    if not (isinstance(declared, list) and declared):
        declared = spec.get("alphabet")
    if isinstance(declared, list) and declared:
        return declared
    out: list[str] = []

    def add(symbols: Any) -> None:
        if isinstance(symbols, list):
            for x in symbols:
                if isinstance(x, str) and x and x not in out:
                    out.append(x)

    def walk(node: Any) -> None:
        if not isinstance(node, dict):
            return
        kind = node.get("kind")
        if kind == "grammar":
            add(node.get("terminals"))
        elif kind == "grammar_filter":
            walk(node.get("grammar"))
        elif kind in _COMPOSITE_OPS:
            for b in node.get("branches") or []:
                walk(b)
        elif kind == "exists_decomposition":
            add(node.get("alphabet"))
            alphabets = node.get("alphabets")
            if isinstance(alphabets, dict):
                for key in node.get("parts") or []:
                    add(alphabets.get(key))
        else:
            add(node.get("alphabet"))

    walk(spec)
    return out or None


# ---------------------------------------------------------------------------
# render_statement (REG direction; "cfl"/"non_cfl"/"dcfl"/"non_dcfl" delegate
# to cfl_system.lib.lean_ir / dcfl_system.lib.lean_ir)
# ---------------------------------------------------------------------------

_DIRECTIONS_REG = {"regular": False, "non_regular": True}
_ALL_DIRECTIONS = {
    "regular", "non_regular", "cfl", "non_cfl", "dcfl", "non_dcfl", "ll",
}


def render_statement(ir: dict, direction: str) -> LeanStatement | None:
    stmt, _reason = render_statement_verbose(ir, direction)
    return stmt


def render_statement_verbose(ir: dict, direction: str) -> tuple[LeanStatement | None, str | None]:
    """``(LeanStatement, None)`` on success, ``(None, reason)`` otherwise.
    Never raises."""
    try:
        return _render_statement_verbose(ir, direction)
    except Exception as exc:  # pragma: no cover - defensive; never raise
        return None, f"internal error: {exc!r}"


def _render_statement_verbose(ir: dict, direction: str) -> tuple[LeanStatement | None, str | None]:
    if direction == "ll":
        return None, (
            "LL(k)-ness is a property of a grammar's parsing algorithm, not "
            "of the language it generates -- not formalized (docs/VERDICT_"
            "POLICY.md R-Lean: 'LL(k) — не формализуется')"
        )
    if direction not in _ALL_DIRECTIONS:
        return None, f"unknown direction {direction!r}"
    if direction not in _DIRECTIONS_REG:
        return None, (
            f"direction {direction!r} is handled by "
            f"{'cfl_system' if direction in ('cfl', 'non_cfl') else 'dcfl_system'}"
            ".lib.lean_ir, not agent_system.lib.lean_ir"
        )
    if not isinstance(ir, dict):
        return None, "ir must be a dict"
    negate = _DIRECTIONS_REG[direction]

    lang_spec = ir.get("language_spec")
    if not isinstance(lang_spec, dict):
        return None, "ir.language_spec is missing or not an object"
    kind = lang_spec.get("kind")

    if kind == "grammar":
        return _render_grammar_case(lang_spec, negate)
    if kind == "regex":
        return _render_regex_case(ir, lang_spec, negate)
    if kind == "natural":
        return _render_natural_case(ir, lang_spec, negate)
    if kind in _COMPOSITE_OPS:
        return _render_composite_case(ir, lang_spec, negate)
    return None, f"unsupported language_spec.kind {kind!r} for direction {direction!r}"


_CFG_IMPORT = "import Mathlib.Computability.ContextFreeGrammar"


def _reg_theorem_decl(negate: bool) -> str:
    prop = "L.IsRegular"
    if negate:
        prop = f"¬ {prop}"
    return f"theorem tfl_main : {prop}"


def _reg_imports(ld: LangDef) -> list[str]:
    imports = ["import TflLean"]
    if "ContextFreeGrammar" in ld.decls:
        imports.append(_CFG_IMPORT)
    return imports


def _regex_lang(lang_spec: dict, sym_map: dict[str, str], suffix: str) -> LangDef | None:
    if lang_spec.get("has_backreferences"):
        return None
    pattern = lang_spec.get("pattern")
    re_expr = parse_regex(pattern, sym_map) if isinstance(pattern, str) else None
    if re_expr is None:
        return None
    return LangDef(
        f"def re{suffix} : RegularExpression Letter := {re_expr}\n\n"
        f"def L{suffix} : Language Letter := re{suffix}.matches'",
        f"def Lb{suffix} (w : List Letter) : Bool := re{suffix}.rmatch w",
    )


def _reg_natural_leaf(spec: dict, sym_map: dict[str, str], suffix: str) -> LangDef | None:
    """One ``natural`` description -> a single language: minimal exponent
    notation, a bare palindrome, or a reversal template."""
    description = spec.get("description")
    if not isinstance(description, str):
        return None
    parsed = _parse_simple_exponent_natural(description)
    if parsed is not None:
        segments, condition = parsed
        body = pattern_body(segments, condition, sym_map)
        if body is not None:
            return set_language(suffix, body, pattern_body(segments, condition, sym_map, decidable=True))
    pal = _palindrome_body(description, sym_map)
    if pal is not None:
        return set_language(suffix, pal, pal)
    tpl = word_template_body(description, sym_map)
    if tpl is not None:
        return set_language(suffix, tpl[0], tpl[1])
    return None


def _reg_leaf(spec: dict, sym_map: dict[str, str], suffix: str) -> LangDef | None:
    kind = spec.get("kind")
    if kind == "grammar":
        text = grammar_decl(spec, sym_map, suffix=suffix)
        return None if text is None else LangDef(text)
    if kind == "regex":
        return _regex_lang(spec, sym_map, suffix)
    if kind == "natural":
        return _reg_natural_leaf(spec, sym_map, suffix)
    return None


def _render_grammar_case(lang_spec: dict, negate: bool) -> tuple[LeanStatement | None, str | None]:
    terminals = lang_spec.get("terminals")
    alpha = alphabet_decl(terminals) if isinstance(terminals, list) else None
    if alpha is None:
        return None, "grammar language_spec missing a usable 'terminals' list"
    alpha_decl, sym_map = alpha
    lang_decl = grammar_decl(lang_spec, sym_map)
    if lang_decl is None:
        return None, "grammar language_spec could not be translated (malformed rules or symbols)"
    ld = LangDef(lang_decl)
    return make_statement(alpha_decl, ld, _reg_theorem_decl(negate), _reg_imports(ld)), None


def _render_regex_case(ir: dict, lang_spec: dict, negate: bool) -> tuple[LeanStatement | None, str | None]:
    if lang_spec.get("has_backreferences"):
        return None, "regex uses backreferences; not expressible as a Mathlib RegularExpression"
    pattern = lang_spec.get("pattern")
    alphabet = lang_spec.get("alphabet") or ir.get("alphabet")
    if not isinstance(pattern, str):
        return None, "regex language_spec missing 'pattern'"
    alpha = alphabet_decl(alphabet)
    if alpha is None:
        return None, "regex language_spec missing a usable alphabet"
    alpha_decl, sym_map = alpha
    ld = _regex_lang(lang_spec, sym_map, "")
    if ld is None:
        return None, (
            f"regex pattern {pattern!r} uses syntax this translator does not "
            "support (only literal alphabet characters, (), |, *, +, ? are)"
        )
    return make_statement(alpha_decl, ld, _reg_theorem_decl(negate), ["import TflLean"]), None


def _render_natural_case(ir: dict, lang_spec: dict, negate: bool) -> tuple[LeanStatement | None, str | None]:
    description = lang_spec.get("description")
    alphabet = ir.get("alphabet") or lang_spec.get("alphabet")
    if not isinstance(description, str):
        return None, "natural language_spec missing 'description'"
    alpha = alphabet_decl(alphabet)
    if alpha is None:
        return None, "no usable alphabet declared in IR for a 'natural' language_spec"
    alpha_decl, sym_map = alpha

    ld = build_language(lang_spec, sym_map, "", _reg_leaf)
    if ld is None:
        return None, (
            "natural-language description is neither simple exponent "
            "notation (whitespace-separated letter^var blocks), a recognized "
            "w = reverse(w) palindrome / reversal-template description, nor a "
            "union/intersection of such -- "
            "cfl_system.lib.lean_ir's full exponent-notation parser may "
            "still handle it for the cfl/dcfl directions"
        )
    return make_statement(alpha_decl, ld, _reg_theorem_decl(negate), _reg_imports(ld)), None


def _render_composite_case(ir: dict, lang_spec: dict, negate: bool) -> tuple[LeanStatement | None, str | None]:
    symbols = composite_alphabet(ir, lang_spec)
    alpha = alphabet_decl(symbols) if symbols else None
    if alpha is None:
        return None, "no usable alphabet declared for a union/intersection language_spec"
    alpha_decl, sym_map = alpha
    ld = build_language(lang_spec, sym_map, "", _reg_leaf)
    if ld is None:
        return None, (
            f"{lang_spec.get('kind')} language_spec has a branch this translator cannot "
            "formalize (each branch must be a grammar, regex, or a natural description "
            "in a supported shape)"
        )
    return make_statement(alpha_decl, ld, _reg_theorem_decl(negate), _reg_imports(ld)), None
